/**
2024.07.01 y.takeda
説明：120.6(SQL Server)の各種伝票ビューを120.12(Oracle)を直接参照する形式に変更する
DB: 192.168.120.6 > cocktail > ビュー
*/


/*o_テーブル*/

--ビュー：o_BMNMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.BMNMTA
CREATE OR ALTER VIEW o_BMNMTA AS
    SELECT
    DATKB, BMNMSTKB, BMNCD, BMNNM, BMNNK, BMNZP, BMNADA, BMNADB, BMNADC,BMNTL, BMNFX, BMNCLAKB, BMNCLBKB, BMNCLCKB, BMNCLAID, BMNCLBID,BMNCLCID, KEIBUMCD, RELFL, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, MPDMSTKB
    FROM OPENQUERY(ORCL,
    '
    SELECT
    DATKB, BMNMSTKB, BMNCD, BMNNM, BMNNK, BMNZP, BMNADA, BMNADB, BMNADC,BMNTL, BMNFX, BMNCLAKB, BMNCLBKB, BMNCLCKB, BMNCLAID, BMNCLBID,BMNCLCID, KEIBUMCD, RELFL, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, MPDMSTKB
    FROM NSY_USR1.BMNMTA
    WHERE DATKB = ''1''
    ')
;

--ビュー：o_BMKMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.BMKMTA
CREATE OR ALTER VIEW o_BMKMTA AS
SELECT
DATKB, BNKCD, BNKNM, BNKKMKCD00, BNKKMKCD01,KOZID00, KOZID01, RELFL, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM OPENQUERY(ORCL,
'SELECT
DATKB, BNKCD, BNKNM, BNKKMKCD00, BNKKMKCD01,KOZID00, KOZID01, RELFL, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM NSY_USR1.BNKMTA
WHERE DATKB =''1''
')
;

--ビュー：o_CLSMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.CLSMTA
CREATE OR ALTER VIEW o_CLSMTA AS
SELECT CLSKB, CLSID, CLSNM, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM OPENQUERY(ORCL,
'SELECT CLSKB, CLSID, CLSNM, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM NSY_USR1.CLSMTA
')
;

--ビュー：o_HINMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.HINMTA
CREATE OR ALTER VIEW o_HINMTA AS
SELECT
DATKB, HINMSTKB, HINCD, HINNMA, HINNMB, HINNK, HINCLAKB, HINCLBKB, HINCLCKB, HINCLAID, HINCLBID, HINCLCID, HINSIRCD, MAKCD, HINCMA,
HINCMB, HINCMC, HINCMD, HINCME, TNABTK00, TNABTK01, TNABTK02, TNABTK03, TNABTK04, TNABTK05, TNABTK06, TNABTK07, TNABTK08, TNABTK09, TNABTK10,
TNABTK11, TNAATK00, TNAATK01, TNAATK02, TNAATK03, TNAATK04, TNAATK05, TNAATK06, TNAATK07, TNAATK08, TNAATK09, TNAATK10, TNAATK11, TNAZTK00,
TNAZTK01, TNAZTK02, TNAZTK03, TNAZTK04, TNAZTK05, TNAZTK06, TNAZTK07, TNAZTK08, TNAZTK09, TNAZTK10, TNAZTK11, LSTUKEDT, LSTUKETK, LSTHARDT,
HINZEIKB, ZEIRNKKB, ZEIRT, HINKB, ZAIKB, UNTCD00, UNTCD01, UNTCD02, UNTNM00, UNTNM01, UNTNM02, IRIASU00, IRIASU01, IRIASU02, HINTKSID, HINJUNKB,
HINNMMKB, IMGNM, JANCD, ITFCD, MRPKB, HRTDD, ORTDD, COLCD, SIZCD, JYURY, YOURY, LOTKB, HINLCDKB, NSZHYJKB, HINLBLKB, AUTLOCID, HATLOTSU,
HATCYLID, KAMCLKB, RELFL, QSYOMKB, QSYOMKSU, QSYOMHSU, QJYURY, QUNSKSU, QLSTURDT, QHIKHSU, QKEISANF, TNATKKB, GENTKAKB, QGNRHTK, QRMHTK,
QKEIHTK, QGRYOKB, QPRDCD, QPRDKB, QKOSKB, QSZUNTCD, QSZUNTNM, QHIKSSB, QHNUNTCD, QHNUNTNM, QKOUNTCD, QKOUNTNM, STTYUNDT, ENDYUNDT,
STTYUGDT, ENDYUGDT, TFKHTK, JYURYCNV, QZAIALKB, HINLCDSB, SPCDT, SPCHANSU, ITFBCD, ITFCCD, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO,
MAKHINCD, SEIHINNMA, SEIHINNMB, SEIYURKB, HOKTEKKB, HATUNTCD, HANUNTCD, TRISTPKB, EANKB, USEKB, HATUNTIN, HANUNTIN, MPDMSTKB, HINHIKTM,
OLDHINCD, MEDCD, MEDACD, MEDBCD, MEDCCD, KOURITK, OROSITK, TOKUYATK, KNRTK, IYAKUKB, DOUYAKKB, DEKYAKKB, KITGIMKB, HOKSEIKB, SYOKANKB,
HOKANKB, TEHAIKB, TZCCD, KSSYOCD, MEKTM, SYOTM, OTPUNTSU, TRISTPDT, HATCD, SODIRISU, MDNOUTKB, IJICDA, IJICDB, KTKBCDA, KTKBCDB, KTKBCDC,
KTKBCDD, KTKBCDE, KTKBCDF, KTKBCDG, KTKBCDH, KTKBCDI, KTKBCDJ, KBYBCDA, KBYBCDB, KBYBCDC, KBYBCDD, KBYBCDE, SIYKB, JAN4CD, COMHINCD,
SUCHINCD, DIRISU, IRITANSU, HINBUNCD, GTINCD, HIKSYRKB, JDHINNK, JSHINNK, JSTRISTTDT, JSTRISTPDT, KIHIRISU, PLTTUMSU, CASGWSU, CASGWUNTCD,
CASSZLSU, CASSZWSU, CASSZHSU, CASSZUNTCD, CASCPSU, CASCPUNTCD, PCEGWSU, PCEGWUNTCD, PCESZLSU, PCESZWSU, PCESZHSU, PCESZUNTCD, PCECPSU,
PCECPUNTCD, NHSKTKB00, NHSKTKB01, NHSKTKB02, NHSKTKB03, YAKKATK, OUTKB, OUTDT, SEISKB
FROM OPENQUERY(ORCL,
'
SELECT
DATKB, HINMSTKB, HINCD, HINNMA, HINNMB, HINNK, HINCLAKB, HINCLBKB, HINCLCKB, HINCLAID, HINCLBID, HINCLCID, HINSIRCD, MAKCD, HINCMA,
HINCMB, HINCMC, HINCMD, HINCME, TNABTK00, TNABTK01, TNABTK02, TNABTK03, TNABTK04, TNABTK05, TNABTK06, TNABTK07, TNABTK08, TNABTK09, TNABTK10,
TNABTK11, TNAATK00, TNAATK01, TNAATK02, TNAATK03, TNAATK04, TNAATK05, TNAATK06, TNAATK07, TNAATK08, TNAATK09, TNAATK10, TNAATK11, TNAZTK00,
TNAZTK01, TNAZTK02, TNAZTK03, TNAZTK04, TNAZTK05, TNAZTK06, TNAZTK07, TNAZTK08, TNAZTK09, TNAZTK10, TNAZTK11, LSTUKEDT, LSTUKETK, LSTHARDT,
HINZEIKB, ZEIRNKKB, ZEIRT, HINKB, ZAIKB, UNTCD00, UNTCD01, UNTCD02, UNTNM00, UNTNM01, UNTNM02, IRIASU00, IRIASU01, IRIASU02, HINTKSID, HINJUNKB,
HINNMMKB, IMGNM, JANCD, ITFCD, MRPKB, HRTDD, ORTDD, COLCD, SIZCD, JYURY, YOURY, LOTKB, HINLCDKB, NSZHYJKB, HINLBLKB, AUTLOCID, HATLOTSU,
HATCYLID, KAMCLKB, RELFL, QSYOMKB, QSYOMKSU, QSYOMHSU, QJYURY, QUNSKSU, QLSTURDT, QHIKHSU, QKEISANF, TNATKKB, GENTKAKB, QGNRHTK, QRMHTK,
QKEIHTK, QGRYOKB, QPRDCD, QPRDKB, QKOSKB, QSZUNTCD, QSZUNTNM, QHIKSSB, QHNUNTCD, QHNUNTNM, QKOUNTCD, QKOUNTNM, STTYUNDT, ENDYUNDT,
STTYUGDT, ENDYUGDT, TFKHTK, JYURYCNV, QZAIALKB, HINLCDSB, SPCDT, SPCHANSU, ITFBCD, ITFCCD, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO,
MAKHINCD, SEIHINNMA, SEIHINNMB, SEIYURKB, HOKTEKKB, HATUNTCD, HANUNTCD, TRISTPKB, EANKB, USEKB, HATUNTIN, HANUNTIN, MPDMSTKB, HINHIKTM,
OLDHINCD, MEDCD, MEDACD, MEDBCD, MEDCCD, KOURITK, OROSITK, TOKUYATK, KNRTK, IYAKUKB, DOUYAKKB, DEKYAKKB, KITGIMKB, HOKSEIKB, SYOKANKB,
HOKANKB, TEHAIKB, TZCCD, KSSYOCD, MEKTM, SYOTM, OTPUNTSU, TRISTPDT, HATCD, SODIRISU, MDNOUTKB, IJICDA, IJICDB, KTKBCDA, KTKBCDB, KTKBCDC,
KTKBCDD, KTKBCDE, KTKBCDF, KTKBCDG, KTKBCDH, KTKBCDI, KTKBCDJ, KBYBCDA, KBYBCDB, KBYBCDC, KBYBCDD, KBYBCDE, SIYKB, JAN4CD, COMHINCD,
SUCHINCD, DIRISU, IRITANSU, HINBUNCD, GTINCD, HIKSYRKB, JDHINNK, JSHINNK, JSTRISTTDT, JSTRISTPDT, KIHIRISU, PLTTUMSU, CASGWSU, CASGWUNTCD,
CASSZLSU, CASSZWSU, CASSZHSU, CASSZUNTCD, CASCPSU, CASCPUNTCD, PCEGWSU, PCEGWUNTCD, PCESZLSU, PCESZWSU, PCESZHSU, PCESZUNTCD, PCECPSU,
PCECPUNTCD, NHSKTKB00, NHSKTKB01, NHSKTKB02, NHSKTKB03, YAKKATK, OUTKB, OUTDT, SEISKB
FROM NSY_USR1.HINMTA
')
;

--ビュー：o_HINMTC
--FROM: [ORCL-LINK].ORCLLINK.dbo.HINMTC
CREATE OR ALTER VIEW o_HINMTC AS
SELECT
SOUCD, HINCD, LOTID, HINLCDDT, HINLCDKB, LOTCM, RELZAISU, FIXLOCID, FSTNYUDT,FSTSYUDT, LSTNYUDT, LSTSYUDT, HINMSTKB, RELFL, OPEID, CLTID,
WRTTM,WRTDT, HIKSU, GNKTK, ZNETNADT, ZNETNASU, ZNETNAKN, ZNEBZNSU,SMAZANDT, SMAZANSU, SMAZANKN, SMABZNSU, LOTAID, LOTBID
FROM OPENQUERY(ORCL,
'
SELECT
SOUCD, HINCD, LOTID, HINLCDDT, HINLCDKB, LOTCM, RELZAISU, FIXLOCID, FSTNYUDT,FSTSYUDT, LSTNYUDT, LSTSYUDT, HINMSTKB, RELFL, OPEID, CLTID,
WRTTM, WRTDT, HIKSU, GNKTK, ZNETNADT, ZNETNASU, ZNETNAKN, ZNEBZNSU,SMAZANDT, SMAZANSU, SMAZANKN, SMABZNSU, LOTAID, LOTBID
FROM NSY_USR1.HINMTC
where ((LOTID <> '' '')or(FSTSYUDT <> '' ''))
')
;

--ビュー：o_IDNTHA
--FROM: [ORCL-LINK].ORCLLINK.dbo.IDNTHA
CREATE OR ALTER VIEW o_IDNTHA AS
SELECT
DATNO, DATKB, DENKB, IDNNO, HDNNO, IDNDT, SMADT, SIRCD, SIRRN,TANCD, KTNCD, SOUCD, TANBMNCD, SOUBMNCD, DENCM, DENCMB, SIRNMMKB,
SDNID, LSTID, SIRMSTKB, TANMSTKB, DKBSB, SDNENDKB, LSTTORDT,OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, JHDCNTNO, HDNSMEKB,IDNSMEKB, UHAKB, DWHKB
FROM OPENQUERY(ORCL,
'
SELECT
DATNO, DATKB, DENKB, IDNNO, HDNNO, IDNDT, SMADT, SIRCD, SIRRN,TANCD, KTNCD, SOUCD, TANBMNCD, SOUBMNCD, DENCM, DENCMB, SIRNMMKB,
SDNID, LSTID, SIRMSTKB, TANMSTKB, DKBSB, SDNENDKB, LSTTORDT,OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, JHDCNTNO, HDNSMEKB,IDNSMEKB, UHAKB, DWHKB
FROM NSY_USR1.IDNTHA
WHERE DATKB =''1''
')
;

--ビュー：o_IDNTRA
--FROM: [ORCL-LINK].ORCLLINK.dbo.IDNTRA
CREATE OR ALTER VIEW o_IDNTRA AS
SELECT
DATNO, DATKB, DENKB, IDNNO, LINNO, HDNNO, HDNLINNO, RECNO, IDNRECNO, IDNDT, SMADT, SIRCD, TANCD, KTNCD, SOUCD, TANBMNCD, SOUBMNCD,
HINCD, HINNMA, HINNMB, MAKCD, HINSIRCD, HINNMMKB, HINKB, ZAIKB, MRPKB, HRTDD, ORTDD, SIZCD, COLCD, UNTCD00, UNTCD01, UNTCD02, UNTNM00,
UNTNM01, UNTNM02, IRISU00, IRISU01, IRISU02, CASSU00, CASSU01, CASSU02, INPSU, SRESU, LINCMA, LINCMB, HATDELSU, LSTID, SIRMSTKB, TANMSTKB,
HINMSTKB, DKBSB, DKBID, DKBNM, UPDID, MHJSQ, DKBZAIFL, NSZHYJKB, LOTKB, HINLCDKB, SUBDSPKB, HEDLOTID, HEDLCTDT, DSPUNTCD, DSPUNTIN,
DSPUNTNM, DSPIRISU, DSPCASSU, DKBFLA, DKBFLB, DKBFLC, DFLDKBCD, OPEID, CLTID, WRTTM, WRTDT, TOKCD, SIRTNKKB, MPDSEQNO, ODNNO, DWHKB, LOTAID,LOTBID, NYUYOTNO
FROM OPENQUERY(ORCL,
'
SELECT
DATNO, DATKB, DENKB, IDNNO, LINNO, HDNNO, HDNLINNO, RECNO, IDNRECNO, IDNDT, SMADT, SIRCD, TANCD, KTNCD, SOUCD, TANBMNCD, SOUBMNCD,
HINCD, HINNMA, HINNMB, MAKCD, HINSIRCD, HINNMMKB, HINKB, ZAIKB, MRPKB, HRTDD, ORTDD, SIZCD, COLCD, UNTCD00, UNTCD01, UNTCD02, UNTNM00,
UNTNM01, UNTNM02, IRISU00, IRISU01, IRISU02, CASSU00, CASSU01, CASSU02, INPSU, SRESU, LINCMA, LINCMB, HATDELSU, LSTID, SIRMSTKB, TANMSTKB,
HINMSTKB, DKBSB, DKBID, DKBNM, UPDID, MHJSQ, DKBZAIFL, NSZHYJKB, LOTKB, HINLCDKB, SUBDSPKB, HEDLOTID, HEDLCTDT, DSPUNTCD, DSPUNTIN,
DSPUNTNM, DSPIRISU, DSPCASSU, DKBFLA, DKBFLB, DKBFLC, DFLDKBCD, OPEID, CLTID, WRTTM, WRTDT, TOKCD, SIRTNKKB, MPDSEQNO, ODNNO, DWHKB, LOTAID,LOTBID, NYUYOTNO
FROM NSY_USR1.IDNTRA
WHERE DATKB = ''1''
')
;

--ビュー：o_IRITRA
--FROM: [ORCL-LINK].ORCLLINK.dbo.IRITRA
CREATE OR ALTER VIEW o_IRITRA AS
SELECT
DATNO, DATKB, DENKB, QIRNO, LINNO, HINCD, HINNMA, HINNMB, MAKCD, HINSIRCD, HINKB, ZAIKB, MRPKB, KOSCASSU, HRTDD, ORTDD, SIZCD, COLCD,
UNTCD00, UNTCD01, UNTCD02, UNTNM00, UNTNM01, UNTNM02, IRISU00, IRISU01, IRISU02, CASSU00, CASSU01, CASSU02, FURSU, GNKFRITK, GNKFRIKN, LINCMA,
LINCMB, LSTID, HINMSTKB, DKBSB, DKBID, DKBNM, UPDID, MHJSQ, DKBTEGFL, DKBZAIFL, LOTKB, HINLCDKB, SUBDSPKB, HEDLOTID, HEDLCTDT, DSPUNTCD,
DSPUNTIN, DSPUNTNM, DSPIRISU, DSPCASSU, DKBFLA, DKBFLB, DKBFLC, DFLDKBCD, ARGGSGTK, ARGGSGKN, OPEID, CLTID, WRTTM, WRTDT, SYUSIJNO
FROM OPENQUERY(ORCL,
'
SELECT
DATNO, DATKB, DENKB, QIRNO, LINNO, HINCD, HINNMA, HINNMB, MAKCD, HINSIRCD, HINKB, ZAIKB, MRPKB, KOSCASSU, HRTDD, ORTDD, SIZCD, COLCD,
UNTCD00, UNTCD01, UNTCD02, UNTNM00, UNTNM01, UNTNM02, IRISU00, IRISU01, IRISU02, CASSU00, CASSU01, CASSU02, FURSU, GNKFRITK, GNKFRIKN, LINCMA,
LINCMB, LSTID, HINMSTKB, DKBSB, DKBID, DKBNM, UPDID, MHJSQ, DKBTEGFL, DKBZAIFL, LOTKB, HINLCDKB, SUBDSPKB, HEDLOTID, HEDLCTDT, DSPUNTCD,
DSPUNTIN, DSPUNTNM, DSPIRISU, DSPCASSU, DKBFLA, DKBFLB, DKBFLC, DFLDKBCD, ARGGSGTK, ARGGSGKN, OPEID, CLTID, WRTTM, WRTDT, SYUSIJNO
FROM NSY_USR1.IRITRA
')
;

--ビュー：o_JDNTHA
--FROM: [ORCL-LINK].ORCLLINK.[dbo].[w_JDNTHA_BF2M] UNION ALL [ORCL-LINK].ORCLLINK.[dbo].[v_JDNTHA_2M]
CREATE OR ALTER VIEW o_JDNTHA AS
SELECT
*
FROM OPENQUERY(ORCL,
'
select
*
from NSY_USR1.JDNTHA
WHERE DATKB = ''1''
')
;
/*要らないカラム
SYUBACID,ROTCD,ROTSHPSQ,DENCMB,TOKSDWKB,TOKKDWKB,MOTDATNO,JHAKB,TOKCLCID,DENCMBCD,DENCMCCD,DENCMC
*/

--ビュー：o_JDNTHA_20150625そのまま全参照版
--FROM: [ORCL-LINK].ORCLLINK.dbo.JDNTHA
CREATE OR ALTER VIEW o_JDNTHA_20150625そのまま全参照版 AS
SELECT
DATNO, DATKB, DENKB, JDNNO, JDNDT, DEFNOKDT, JUCSYYDT, SMADT, TOKCD, TOKRN, NHSCD, NHSRN, TOKSEICD, TANCD, KTNCD, SOUCD, TANBMNCD,
TOKBMNCD, SOUBMNCD, SBAUODKN, SBAJZEKN, SBAJZKKN, SYUBACID, ROTCD, ROTSHPSQ, DENCM, DENCMB, TOKSMEKB, TOKSMEDD, TOKSMECC, TOKSDWKB,
TOKKESDD, TOKKESCC, TOKKDWKB, TOKZEIKB, TOKZCLKB, TOKRPSKB, TOKZRNKB, TOKNMMKB, NHSNMMKB, ADNID, LSTID, TOKMSTKB, NHSMSTKB, TANMSTKB,
NHSKB, DKBSB, TOKNKDKB, JDNENDKB, ODNKB, ODNENDKB, UDNENDKB, SVCKB, SVCENDKB, URIKJNKB, LSTTORDT, MOTDATNO, OPEID, CLTID, WRTTM, WRTDT,
CRTTM, CRTDT, UPDCNTNO, TRNNO, CSVDATNO, JHAKB, JDNSMEKB, TOKCLAKB, TOKCLBKB, TOKCLCKB, TOKCLAID, TOKCLBID, TOKCLCID, PIKHAKKB, SBAGNKKN,
ALSKB, KRDKB, JUCKB, HSSRN, HSSZP, HSSADA, HSSADB, HSSADC, HSSTL, HSSFX, DENCMBCD, DENCMCCD, DENCMC, QUNSID
FROM OPENQUERY(ORCL,
'
SELECT * FROM NSY_USR1.JDNTHA
')
;

--ビュー：o_JDNTRA
--FROM: [ORCL-LINK].ORCLLINK.dbo.JDNTRA
CREATE OR ALTER VIEW o_JDNTRA AS
SELECT
*
FROM OPENQUERY(ORCL,
'
select
*
from NSY_USR1.JDNTRA
WHERE DATKB = ''1''
')
;
/*要らないカラム:
HRTDD,ORTDD,SIZCD,UNTCD01,UNTCD02,UNTMN01,UNTMN02,SYUBACID,ROTID,ROTSHPSQ,LINCMA,LINCMB,DKBFLA,DKBFLB,DKBFLC,DFLDKBCD,MOTDATNO,HDNNO,JIGCD,JIGNM,MAKHINCD,EOSHINID,EOSHINNA,EOSHINNB,AUTHDNNO,SIRTNKKB,ERRCM
*/


--ビュー：o_JGTTRA_1M
--FROM: [ORCL-LINK].ORCLLINK.dbo.JGTTRA_1M
CREATE OR ALTER VIEW o_JGTTRA_1M AS
SELECT
DATNO, LINNO, UPDMODKB, CSVDATNO, CSVLINNO, MDSHIKIB, MDOROCD, MDIRYOCD, MDSUBNO, MDCRTDT, MDCRTTM, MDHATNO, MDFUKCD, MDHATDT,
MDHINKB, MDGTINCD, MDGTINNM, MDHATSU, MDNOKDT, MDNHSBA, MDMAEKB, MDMAECD, TOKCD, NHSCD, SOUCD, TANCD, JDNDT, DKBID, HINCD, UODTK,
UODKN, ERRNO, ERRCM, JDNNO, JDNLINNO, SYONO, OPEID, CLTID, WRTTM, WRTDT, JUCSYYDT, STSFL, SYODT
FROM OPENQUERY(ORCL,
'
SELECT
DATNO, LINNO, UPDMODKB, CSVDATNO, CSVLINNO, MDSHIKIB, MDOROCD, MDIRYOCD, MDSUBNO, MDCRTDT, MDCRTTM, MDHATNO, MDFUKCD, MDHATDT,
MDHINKB, MDGTINCD, MDGTINNM, MDHATSU, MDNOKDT, MDNHSBA, MDMAEKB, MDMAECD, TOKCD, NHSCD, SOUCD, TANCD, JDNDT, DKBID, HINCD, UODTK,
UODKN, ERRNO, ERRCM, JDNNO, JDNLINNO, SYONO, OPEID, CLTID, WRTTM, WRTDT, JUCSYYDT, STSFL, SYODT
FROM NSY_USR1.JGTTRA
where SYODT >= to_char(ADD_MONTHS(sysdate, - 1), ''yyyymmdd'')
')
;

--ビュー：o_JMDTRA_1M
--FROM: [ORCL-LINK].ORCLLINK.dbo.JMDTRA_1M
CREATE OR ALTER VIEW o_JMDTRA_1M AS
SELECT
DATNO, LINNO, UPDMODKB, CSVDATNO, CSVLINNO, MDSHIKIB, MDOROCD, MDIRYOCD, MDSUBNO, MDCRTDT, MDCRTTM, MDHATNO, MDFUKCD, MDHATDT,
MDHINKB, MDGTINCD, MDGTINNM, MDHATSU, MDNOKDT, MDNHSBA, MDMAEKB, MDMAECD, TOKCD, NHSCD, SOUCD, TANCD, JDNDT, DKBID, HINCD, UODTK,
UODKN, ERRNO, ERRCM, JDNNO, JDNLINNO, SYONO, OPEID, CLTID, WRTTM, WRTDT, JUCSYYDT, STSFL, SYODT
FROM OPENQUERY(ORCL,
'
SELECT
DATNO, LINNO, UPDMODKB, CSVDATNO, CSVLINNO, MDSHIKIB, MDOROCD, MDIRYOCD, MDSUBNO, MDCRTDT, MDCRTTM, MDHATNO, MDFUKCD, MDHATDT,
MDHINKB, MDGTINCD, MDGTINNM, MDHATSU, MDNOKDT, MDNHSBA, MDMAEKB, MDMAECD, TOKCD, NHSCD, SOUCD, TANCD, JDNDT, DKBID, HINCD, UODTK,
UODKN, ERRNO, ERRCM, JDNNO, JDNLINNO, SYONO, OPEID, CLTID, WRTTM, WRTDT, JUCSYYDT, STSFL, SYODT
FROM NSY_USR1.JSCTRA
where SYODT >= to_char(ADD_MONTHS(sysdate, - 1), ''yyyymmdd'')
')
;

--ビュー：o_JSCTRA_1M
--FROM: [ORCL-LINK].ORCLLINK.dbo.JSCTRA_1M
CREATE OR ALTER VIEW o_JSCTRA_1M AS
SELECT
DATNO, LINNO, UPDMODKB, CSVDATNO, CSVLINNO, MDSHIKIB, MDOROCD, MDIRYOCD, MDSUBNO, MDCRTDT, MDCRTTM, MDHATNO, MDFUKCD, MDHATDT,
MDHINKB, MDGTINCD, MDGTINNM, MDHATSU, MDNOKDT, MDNHSBA, MDMAEKB, MDMAECD, TOKCD, NHSCD, SOUCD, TANCD, JDNDT, DKBID, HINCD, UODTK,
UODKN, ERRNO, ERRCM, JDNNO, JDNLINNO, SYONO, OPEID, CLTID, WRTTM, WRTDT, JUCSYYDT, STSFL, SYODT
FROM OPENQUERY(ORCL,
'
SELECT
DATNO, LINNO, UPDMODKB, CSVDATNO, CSVLINNO, MDSHIKIB, MDOROCD, MDIRYOCD, MDSUBNO, MDCRTDT, MDCRTTM, MDHATNO, MDFUKCD, MDHATDT,
MDHINKB, MDGTINCD, MDGTINNM, MDHATSU, MDNOKDT, MDNHSBA, MDMAEKB, MDMAECD, TOKCD, NHSCD, SOUCD, TANCD, JDNDT, DKBID, HINCD, UODTK,
UODKN, ERRNO, ERRCM, JDNNO, JDNLINNO, SYONO, OPEID, CLTID, WRTTM, WRTDT, JUCSYYDT, STSFL, SYODT
FROM NSY_USR1.JSCTRA
where SYODT >= to_char(ADD_MONTHS(sysdate, - 1), ''yyyymmdd'')
')
;

--ビュー：o_JTNTRA_1M
--FROM: [ORCL-LINK].ORCLLINK.dbo.JTNTRA_1M
CREATE OR ALTER VIEW o_JTNTRA_1M AS
SELECT
DATNO, LINNO, UPDMODKB, CSVDATNO, CSVLINNO, THDNDT, TNATSCD, TNHTMCD,
TNHINCD, TNHINNM, TNUODSU, TNSYUKB, TNNOKDT, TNLINCM, TOKCD,
NHSCD, SOUCD, TANCD, JDNDT, DKBID, HINCD, UODTK, UODKN, STSFL,
SYODT, ERRNO, ERRCM, JDNNO, JDNLINNO, SYONO, OPEID, CLTID, WRTTM, WRTDT,
JUCSYYDT, TNHTMNM, TNHINKB, TNHATSB, TNUODTK, TNSEISB, TNKEINO, TNINNAIBA
FROM OPENQUERY(ORCL,
'
SELECT
DATNO, LINNO, UPDMODKB, CSVDATNO, CSVLINNO, THDNDT, TNATSCD, TNHTMCD,
TNHINCD, TNHINNM, TNUODSU, TNSYUKB, TNNOKDT, TNLINCM, TOKCD,
NHSCD, SOUCD, TANCD, JDNDT, DKBID, HINCD, UODTK, UODKN, STSFL,
SYODT, ERRNO, ERRCM, JDNNO, JDNLINNO, SYONO, OPEID, CLTID, WRTTM, WRTDT,
JUCSYYDT, TNHTMNM, TNHINKB, TNHATSB, TNUODTK, TNSEISB, TNKEINO, TNINNAIBA
FROM NSY_USR1.JTNTRA
where SYODT >= to_char(ADD_MONTHS(sysdate, - 1), ''yyyymmdd'')
')
;

--ビュー：o_KTNMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.KTNMTA
CREATE OR ALTER VIEW o_KTNMTA AS
SELECT
DATKB, KTNCD, KTNNMA, KTNNMB, KTNRN, KTNNK, KTNZP, KTNADA, KTNADB, KTNADC, KTNTL, KTNFX, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, MPDMSTKB
FROM OPENQUERY(ORCL,
'
SELECT
DATKB, KTNCD, KTNNMA, KTNNMB, KTNRN, KTNNK, KTNZP, KTNADA, KTNADB, KTNADC, KTNTL, KTNFX, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, MPDMSTKB
FROM NSY_USR1.KTNMTA
WHERE DATKB = ''1''
')
;

--ビュー：o_MAKMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.MAKMTA
CREATE OR ALTER VIEW o_MAKMTA AS
SELECT
DATKB, MAKCD, MAKNM, RELFL, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, MPDMSTKB, MAKNMA, MAKNMB, MAKRN, MAKNK, MAKZP, MAKADA, MAKADB, MAKADC, MAKTL, MAKFX, MEKSEIKB, MEKYNUKB, MEKHATKB
FROM OPENQUERY(ORCL,
'
SELECT
DATKB, MAKCD, MAKNM, RELFL, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, MPDMSTKB, MAKNMA, MAKNMB, MAKRN, MAKNK, MAKZP, MAKADA, MAKADB, MAKADC, MAKTL, MAKFX, MEKSEIKB, MEKYNUKB, MEKHATKB
FROM NSY_USR1.MAKMTA
WHERE DATKB = ''1''
')
;

--ビュー：o_MDNTHA
--FROM: [ORCL-LINK].ORCLLINK.dbo.MDNTHA
CREATE OR ALTER VIEW o_MDNTHA AS
SELECT
DATNO, DATKB, DENKB, MDNNO, DENDT, SMADT, KTNCD,
SOUCD, BMNCD, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO,
TRNNO, MDNSMEKB, TOKCD, LDNNO, LDNCNTNO, IDOHAKKB,
CRTTM, CRTDT, DEFCRTTM, DEFCRTDT, SPDDENNO, SPDEDANO,
SPDDENKB, SPDDATKB, DWHKB, SYUSIJNO
FROM OPENQUERY(ORCL,
'
SELECT
DATNO, DATKB, DENKB, MDNNO, DENDT, SMADT, KTNCD,
SOUCD, BMNCD, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO,
TRNNO, MDNSMEKB, TOKCD, LDNNO, LDNCNTNO, IDOHAKKB,
CRTTM, CRTDT, DEFCRTTM, DEFCRTDT, SPDDENNO, SPDEDANO,
SPDDENKB, SPDDATKB, DWHKB, SYUSIJNO
FROM NSY_USR1.MDNTHA
WHERE DATKB = ''1''
')
;

--ビュー：o_MDNTRA
--FROM: [ORCL-LINK].ORCLLINK.dbo.MDNTRA
CREATE OR ALTER VIEW o_MDNTRA AS
SELECT
DATNO, DATKB, DENKB, MDNNO, LINNO, MDNRECNO, DENDT, SMADT, KTNCD, SOUCD, BMNCD, HINCD, HINNMA, HINNMB, MAKCD, HINSIRCD, HINKB, ZAIKB,
MRPKB, KOSCASSU, HRTDD, ORTDD, SIZCD, COLCD, UNTCD00, UNTCD01, UNTCD02, UNTNM00, UNTNM01, UNTNM02, IRISU00, IRISU01, IRISU02, CASSU00,
CASSU01, CASSU02, FURSU, GNKFRITK, GNKFRIKN, LINCMA, LINCMB, LSTID, HINMSTKB, DKBSB, DKBID, DKBNM, UPDID, MHJSQ, DKBTEGFL, DKBZAIFL, LOTKB,
HINLCDKB, SUBDSPKB, HEDLOTID, HEDLCTDT, DSPUNTCD, DSPUNTIN, DSPUNTNM, DSPIRISU, DSPCASSU, DKBFLA, DKBFLB, DKBFLC, DFLDKBCD, ARGGSGTK,
ARGGSGKN, OPEID, CLTID, WRTTM, WRTDT, MPDSEQNO, LDNNO, LDNLINNO, LDNRECNO, EOSHINID, EOSHINNA, EOSHINNB, SPDDENNO, SPDLINNO, SPDEDANO,
SPDDENKB, SPDDATKB, SPDTRIKB, DWHKB
FROM OPENQUERY(ORCL,
'
SELECT
DATNO, DATKB, DENKB, MDNNO, LINNO, MDNRECNO, DENDT, SMADT, KTNCD, SOUCD, BMNCD, HINCD, HINNMA, HINNMB, MAKCD, HINSIRCD, HINKB, ZAIKB,
MRPKB, KOSCASSU, HRTDD, ORTDD, SIZCD, COLCD, UNTCD00, UNTCD01, UNTCD02, UNTNM00, UNTNM01, UNTNM02, IRISU00, IRISU01, IRISU02, CASSU00,
CASSU01, CASSU02, FURSU, GNKFRITK, GNKFRIKN, LINCMA, LINCMB, LSTID, HINMSTKB, DKBSB, DKBID, DKBNM, UPDID, MHJSQ, DKBTEGFL, DKBZAIFL, LOTKB,
HINLCDKB, SUBDSPKB, HEDLOTID, HEDLCTDT, DSPUNTCD, DSPUNTIN, DSPUNTNM, DSPIRISU, DSPCASSU, DKBFLA, DKBFLB, DKBFLC, DFLDKBCD, ARGGSGTK,
ARGGSGKN, OPEID, CLTID, WRTTM, WRTDT, MPDSEQNO, LDNNO, LDNLINNO, LDNRECNO, EOSHINID, EOSHINNA, EOSHINNB, SPDDENNO, SPDLINNO, SPDEDANO,
SPDDENKB, SPDDATKB, SPDTRIKB, DWHKB
FROM
NSY_USR1.MDNTRA
WHERE DATKB = ''1''
')
;
/*使ってない?：HRTDD,ORTDD,SIZCD,UNTCD01,UNTCD02,UNTNM01,UNTNM02,LSTID,DKBFLA,DKBFLB,DKBFLC,DFLDKBCD,MPDSEQNO,LDNLINNO,LDNRECNO*/

--ビュー：o_MEIMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.MEIMTA
CREATE OR ALTER VIEW o_MEIMTA AS
SELECT
DATKB, MEISB, MEICD, MEINM, MEIRN, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM OPENQUERY(ORCL,
'
SELECT
DATKB, MEISB, MEICD, MEINM, MEIRN, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM
NSY_USR1.MEIMTA
')
;

--ビュー：o_NHSMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.NHSMTA
CREATE OR ALTER VIEW o_NHSMTA AS
SELECT
DATKB, NHSMSTKB, NHSCD, NHSKB, NHSNMA, NHSNMB, NHSRN, NHSNK,
NHSZP, NHSADA, NHSADB, NHSADC, NHSTL, NHSFX, NHSBOSNM, NHSCTANM,
NHSCLAKB, NHSCLBKB, NHSCLCKB, NHSCLAID, NHSCLBID, NHSCLCID, NHSNMMKB,
RELFL, LSTTORDT, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO,
MPDMSTKB, INTUNSID, JDORSCD, JDORSSCD, JDORSDCD, CHAKUUNSID, EOSMISID,
QAREAID, QCITYID, OUTKB, OUTDT, MDFUKCD, SDFUKCD, GTFUKCD
FROM OPENQUERY(ORCL,
'
SELECT
DATKB, NHSMSTKB, NHSCD, NHSKB, NHSNMA, NHSNMB, NHSRN, NHSNK,
NHSZP, NHSADA, NHSADB, NHSADC, NHSTL, NHSFX, NHSBOSNM, NHSCTANM
NHSCLAKB, NHSCLBKB, NHSCLCKB, NHSCLAID, NHSCLBID, NHSCLCID, NHSNMMKB,
RELFL, LSTTORDT, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO,
MPDMSTKB, INTUNSID, JDORSCD, JDORSSCD, JDORSDCD, CHAKUUNSID, EOSMISID,
QAREAID, QCITYID, OUTKB, OUTDT, MDFUKCD, SDFUKCD, GTFUKCD
FROM NSY_USR1.NHSMTA
where DATKB = ''1''
')
;

--ビュー：o_ODNTHA
--FROM: [ORCL-LINK].ORCLLINK.dbo.ODNTHA
CREATE OR ALTER VIEW o_ODNTHA AS
SELECT
*
FROM OPENQUERY(ORCL,
'
select
*
from NSY_USR1.ODNTHA
WHERE DATKB = ''1''
')
;
/*いる行:
DATNO,DATKB,DENKB,ODNNO,JDNNO,ODNDT,SMADT,TOKCD,TOKRN,NHSCD,NHSRN,TANCD,KTNCD,SOUCD,TANBMNCD,SOUBMNCD,DENCM,TOKNMMKB,NHSNMMKB,ADNID,LSTID,TOKMSTKB,NHSMSTKB,TANMSTKB,NHSKB,DHAKB,DKBSB,UDNENDKB,LSTTORDT
,OPEID,CLTID,WRTTM,WRTDT,UPDCNTNO,TRNNO,JHDCNTNO,JDNSMEKB,TOKCLAKB,TOKCLBKB,TOKCLCKB,TOKCLAID,TOKCLBID,ODNSMEKB
*/

--ビュー：o_ODNTRA
--FROM: [ORCL-LINK].ORCLLINK.dbo.ODNTRA
CREATE OR ALTER VIEW o_ODNTRA AS
SELECT
*
FROM OPENQUERY(ORCL,
'
select
*
from NSY_USR1.ODNTRA
WHERE DATKB = ''1''
')
;
/*いらない行:
SIZCD,UNTCD01,UNTCD02,UNTNM01,UNTNM02,LINCMA,LINCMB,ROTCD,ROTSHPSQ,SUBDSPKB,DKBFLA,DKBFLB,DKBFLC,DFLDKBCD,JIGCD,JIGNM,MPDSEQNO,IDNNO,EOSHINID,EOSHINNA,EOSHINNB,DWHKB,SYUSIJNO
*/

--ビュー：o_SDNTHA
--FROM: [ORCL-LINK].ORCLLINK.dbo.SDNTHA
CREATE OR ALTER VIEW o_SDNTHA AS
SELECT
DATNO, DATKB, DENKB, SDNNO, IDNNO, HDNNO, SDNDT, SMADT, NXTKB,
SSADT, KESDT, SIRCD, SIRRN, SIRSHACD, TANCD, SOUCD, TANBMNCD,
SIRBMNCD, SOUBMNCD, HDNENDKB, SBASREKN, SBASZEKN, SBASZKKN,
SBAPAYKN, DENCM, DENCMB, SIRSMEKB, SIRSMEDD, SIRSMECC, SIRSDWKB,
SIRKESDD, SIRKESCC, SIRKDWKB, SIRZEIKB, SIRZCLKB, SIRRPSKB,
SIRZRNKB, SIRNMMKB, SDNID, LSTID, TANMSTKB, SIRMSTKB, SPAKB,
CSHKB, DKBSB, MOTDATNO, OPEID, CLTID, WRTTM, WRTDT, CRTTM,
CRTDT, UPDCNTNO, TRNNO, JHDCNTNO, OIDCNTNO, HDNSMEKB, UHAKB,
SPDNETKB, SPDDENNO, SPDEDANO, HDNSOUCD, HDNSOUNM, KDNHDNKB,
SPDDENKB, SPDDATKB, DELSSADT, DWHKB, XRNHDNNO
FROM OPENQUERY(ORCL,
'
SELECT
DATNO, DATKB, DENKB, SDNNO, IDNNO, HDNNO, SDNDT, SMADT, NXTKB,
SSADT, KESDT, SIRCD, SIRRN, SIRSHACD, TANCD, SOUCD, TANBMNCD,
SIRBMNCD, SOUBMNCD, HDNENDKB, SBASREKN, SBASZEKN, SBASZKKN,
SBAPAYKN, DENCM, DENCMB, SIRSMEKB, SIRSMEDD, SIRSMECC, SIRSDWKB,
SIRKESDD, SIRKESCC, SIRKDWKB, SIRZEIKB, SIRZCLKB, SIRRPSKB,
SIRZRNKB, SIRNMMKB, SDNID, LSTID, TANMSTKB, SIRMSTKB, SPAKB,
CSHKB, DKBSB, MOTDATNO, OPEID, CLTID, WRTTM, WRTDT, CRTTM,
CRTDT, UPDCNTNO, TRNNO, JHDCNTNO, OIDCNTNO, HDNSMEKB, UHAKB,
SPDNETKB, SPDDENNO, SPDEDANO, HDNSOUCD, HDNSOUNM, KDNHDNKB,
SPDDENKB, SPDDATKB, DELSSADT, DWHKB, XRNHDNNO
FROM NSY_USR1.SDNTHA
where DATKB = ''1''
')
;

--ビュー：o_SDNTRA
--FROM: [ORCL-LINK].ORCLLINK.dbo.SDNTRA
CREATE OR ALTER VIEW o_SDNTRA AS
SELECT
DATNO, DATKB, DENKB, SDNNO, LINNO, IDNNO, IDNLINNO, HDNNO, HDNLINNO, RECNO, IDNRECNO, SDNDT, SMADT, SSADT, KESDT, SIRCD, SIRSHACD, TANCD,
SOUCD, TANBMNCD, SIRBMNCD, SOUBMNCD, HINCD, HINNMA, HINNMB, MAKCD, HINSIRCD, HINNMMKB, HINKB, ZAIKB, MRPKB, HRTDD, ORTDD, SIZCD,
COLCD, UNTCD, UNTIN, UNTNM, IRISU, CASSU, SRESU, SRETK, SREKN, SZEKN, ZKMSZEKN, ZNKSREKN, SODTK, PAYKN, LINCMA, LINCMB, HATDELSU, BNKCD,
TEGNO, TEGDT, HINZEIKB, ZEIRNKKB, ZEIRT, LSTID, SIRMSTKB, TANMSTKB, HINMSTKB, DKBSB, DKBID, DKBNM, UPDID, MHJSQ, DKBTEGFL, DKBZAIFL, DKBFLA,
DKBFLB, DKBFLC, DFLDKBCD, MOTDATNO, OPEID, CLTID, WRTTM, WRTDT, CRTTM, CRTDT, TOKCD, SIRTNKKB, UDNNO, HINZEINM, SDNSTSKB, SYOTAIKB, SPDDENNO,
SPDLINNO, SPDEDANO, NHSDT, SDNNHSID, ISNKB, HDNSOUCD, HDNSOUNM, KNRTK, SPDDENKB, SPDDATKB, SPDTRIKB, DWHKB, SPDIRISU, SPDCASSU, SPDSRETK,
NYUYOTNO, NHSCD
FROM OPENQUERY(ORCL,
'
SELECT
DATNO, DATKB, DENKB, SDNNO, LINNO, IDNNO, IDNLINNO, HDNNO, HDNLINNO, RECNO, IDNRECNO, SDNDT, SMADT, SSADT, KESDT, SIRCD, SIRSHACD, TANCD,
SOUCD, TANBMNCD, SIRBMNCD, SOUBMNCD, HINCD, HINNMA, HINNMB, MAKCD, HINSIRCD, HINNMMKB, HINKB, ZAIKB, MRPKB, HRTDD, ORTDD, SIZCD,
COLCD, UNTCD, UNTIN, UNTNM, IRISU, CASSU, SRESU, SRETK, SREKN, SZEKN, ZKMSZEKN, ZNKSREKN, SODTK, PAYKN, LINCMA, LINCMB, HATDELSU, BNKCD,
TEGNO, TEGDT, HINZEIKB, ZEIRNKKB, ZEIRT, LSTID, SIRMSTKB, TANMSTKB, HINMSTKB, DKBSB, DKBID, DKBNM, UPDID, MHJSQ, DKBTEGFL, DKBZAIFL, DKBFLA,
DKBFLB, DKBFLC, DFLDKBCD, MOTDATNO, OPEID, CLTID, WRTTM, WRTDT, CRTTM, CRTDT, TOKCD, SIRTNKKB, UDNNO, HINZEINM, SDNSTSKB, SYOTAIKB, SPDDENNO,
SPDLINNO, SPDEDANO, NHSDT, SDNNHSID, ISNKB, HDNSOUCD, HDNSOUNM, KNRTK, SPDDENKB, SPDDATKB, SPDTRIKB, DWHKB, SPDIRISU, SPDCASSU, SPDSRETK,
NYUYOTNO, NHSCD FROM NSY_USR1.SDNTRA
where datkb = ''1''
')
;

--ビュー：o_SEITRA
--FROM: [ORCL-LINK].ORCLLINK.dbo.SEITRA
CREATE OR ALTER VIEW o_SEITRA AS
SELECT
SSADT, TOKCD, KAIZEIKB, SEINO, SEIVERSU, CLRCNTSU, SMEFL, SEIPRYKB, PRTFL, FSTPRTDT, FSTPRTTM, RUNFL, OPEID, CLTID, WRTTM, WRTDT, TRNNO
FROM OPENQUERY(ORCL,
'
SELECT
SSADT, TOKCD, KAIZEIKB, SEINO, SEIVERSU, CLRCNTSU, SMEFL, SEIPRYKB, PRTFL, FSTPRTDT, FSTPRTTM, RUNFL, OPEID, CLTID, WRTTM, WRTDT, TRNNO
FROM NSY_USR1.SEITRA
')
;

--ビュー：o_SEKPR81
--FROM: [ORCL-LINK].ORCLLINK.dbo.SEKPR81
CREATE OR ALTER VIEW o_SEKPR81 AS
SELECT
RPTCLTID, SEINO, TOKCD, UDNDT, PRTCM, DENKB, UDNNO, LINNO, TOKZP, TOKADA, TOKADB, TOKADC, TOKNMA, TOKNMB, TOKSEICD, KONSMEDT, DENSU,
TOUKAIDT, ZSZSEIKN, SSANYUKN, ZSAKRIKN, SSAURIKN, SSANEBKN, SSAUZEKN, SSASEIKN, TOKRN, DKBNM, HINCD, EOSHINNA, EOSHINNB, URISU, URITK, NYUKN,
UZEKN, URIKN, HINZEIKB, ADJKN, CASSU, DATNO, IRISU, NEGKB, TOKSU, TOKZEIKB, UNTNM, WRTTM, WRTDT, TOKZCLKB, DSPKB, SEIVERSU, TSTCM, USRZP00,
USRADA00, USRADB00, USRADC00, USRNMA00, USRNMB00, USRTL00, USRFX00, USRZP01, USRADA01, USRADB01, USRADC01, USRNMA01, USRNMB01, USRTL01,
USRFX01, TANCD, TOKSMEDD, DKBID, PAGNO, SOFUNMA, SOFUNMB
FROM OPENQUERY(ORCL,
'
SELECT
RPTCLTID, SEINO, TOKCD, UDNDT, PRTCM, DENKB, UDNNO, LINNO, TOKZP, TOKADA, TOKADB, TOKADC, TOKNMA, TOKNMB, TOKSEICD, KONSMEDT, DENSU,
TOUKAIDT, ZSZSEIKN, SSANYUKN, ZSAKRIKN, SSAURIKN, SSANEBKN, SSAUZEKN, SSASEIKN, TOKRN, DKBNM, HINCD, EOSHINNA, EOSHINNB, URISU, URITK, NYUKN,
UZEKN, URIKN, HINZEIKB, ADJKN, CASSU, DATNO, IRISU, NEGKB, TOKSU, TOKZEIKB, UNTNM, WRTTM, WRTDT, TOKZCLKB, DSPKB, SEIVERSU, TSTCM, USRZP00,
USRADA00, USRADB00, USRADC00, USRNMA00, USRNMB00, USRTL00, USRFX00, USRZP01, USRADA01, USRADB01, USRADC01, USRNMA01, USRNMB01, USRTL01,
USRFX01, TANCD, TOKSMEDD, DKBID, PAGNO, SOFUNMA, SOFUNMB
FROM NSY_USR9.SEKPR81
')
;

--ビュー：o_SIRMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.SIRMTA
CREATE OR ALTER VIEW o_SIRMTA AS
SELECT
DATKB, SIRMSTKB, SIRCD, SIRNMA, SIRNMB, SIRRN, SIRNK, SIRZP, SIRADA, SIRADB, SIRADC, SIRTL, SIRFX, SIRBOSNM, SIRCTANM, SIRCLAKB, SIRCLBKB, SIRCLCKB,
SIRCLAID, SIRCLBID, SIRCLCID, TANCD, SIRBMNCD, KAKZANDT, KAKZANKN, SHAZANDT, SHAZANKN, SMAZANDT, SMAZANKN, SSAZANDT, SSAZANKN, LSTTORDT,
SIRSMEKB, SIRSMEDD, SIRSMECC, SIRSDWKB, TOSKIJFL, SIRKESDD, SIRKESCC, SIRKDWKB, MMNGNSKN, MMNGNSKB, IJYSHAKB00, IJYSHAKB01, IJYSHAKB02,
IJYSHAKB03, IJYSHAKB04, IJYSHART00, IJYSHART01, IJYSHART02, IJYSHART03, IJYSHART04, SHATEGST00, SHATEGST01, SHATEGST02, SHATEGST03, SHATEGST04,
FIXGNSKN, SHAFKMFL, STGYSOFL, SHAFL, SIRZEIKB, SIRZCLKB, SIRRPSKB, SIRZRNKB, SIRSHACD, TNKKB, SIRTKSID, STKKRHKB, SKNKRHKB, SIRNMMKB, SIRSUMCD,
SIRJUNKB, EOSMISID, EOSTORID, KEISIRCD, BNKCD, KOZSYUID, SIRKOZID, LSTID, RELFL, RUNSSADT, RUNSSBDT, RUNCHGKB, OPEID, CLTID, WRTTM, WRTDT,
UPDCNTNO, TRNNO, MPDMSTKB, SIRSIKKB, KOZNM, SIRHOSDT, SIRHOKNA, SIRHOKNB, SIRTEGNM, SIRTEGZP, SIRTEADA, SIRTEADB, SIRTEADC, KKATFL, SHACMA,
SHACMB, MDSKRKB, SHAMOTKB, MDNETOUTKB, QCITYID, OUTKB, OUTDT
FROM OPENQUERY(ORCL,
'
SELECT
DATKB, SIRMSTKB, SIRCD, SIRNMA, SIRNMB, SIRRN, SIRNK, SIRZP, SIRADA, SIRADB, SIRADC, SIRTL, SIRFX, SIRBOSNM, SIRCTANM, SIRCLAKB, SIRCLBKB, SIRCLCKB,
SIRCLAID, SIRCLBID, SIRCLCID, TANCD, SIRBMNCD, KAKZANDT, KAKZANKN, SHAZANDT, SHAZANKN, SMAZANDT, SMAZANKN, SSAZANDT, SSAZANKN, LSTTORDT,
SIRSMEKB, SIRSMEDD, SIRSMECC, SIRSDWKB, TOSKIJFL, SIRKESDD, SIRKESCC, SIRKDWKB, MMNGNSKN, MMNGNSKB, IJYSHAKB00, IJYSHAKB01, IJYSHAKB02,
IJYSHAKB03, IJYSHAKB04, IJYSHART00, IJYSHART01, IJYSHART02, IJYSHART03, IJYSHART04, SHATEGST00, SHATEGST01, SHATEGST02, SHATEGST03, SHATEGST04,
FIXGNSKN, SHAFKMFL, STGYSOFL, SHAFL, SIRZEIKB, SIRZCLKB, SIRRPSKB, SIRZRNKB, SIRSHACD, TNKKB, SIRTKSID, STKKRHKB, SKNKRHKB, SIRNMMKB, SIRSUMCD,
SIRJUNKB, EOSMISID, EOSTORID, KEISIRCD, BNKCD, KOZSYUID, SIRKOZID, LSTID, RELFL, RUNSSADT, RUNSSBDT, RUNCHGKB, OPEID, CLTID, WRTTM, WRTDT,
UPDCNTNO, TRNNO, MPDMSTKB, SIRSIKKB, KOZNM, SIRHOSDT, SIRHOKNA, SIRHOKNB, SIRTEGNM, SIRTEGZP, SIRTEADA, SIRTEADB, SIRTEADC, KKATFL, SHACMA,
SHACMB, MDSKRKB, SHAMOTKB, MDNETOUTKB, QCITYID, OUTKB, OUTDT
FROM NSY_USR1.SIRMTA
WHERE DATKB = ''1''
')
;

--ビュー：o_SJSWRA
--FROM: [ORCL-LINK].ORCLLINK.dbo.SJSWRA
CREATE OR ALTER VIEW o_SJSWRA AS
SELECT
SYONO, KOUKB, PLTCD, DENKB, SYUSIJNO, DENNO, SYUYTIDT, ODNDT,
NOUYTIDT, HAITM, QUNSID, TYAKBKB, COOLKB, TIMESKB, QKOGSU, TOKCD, NHSCD, LINNO,
SYUSIJLINNO, OKRJNO, HINCD, SOUCD, LOTID, TORSU, STSFL, ERRNO, ERRCM, OPEID, CLTID, WRTTM, WRTDT
FROM OPENQUERY(ORCL,
'
SELECT
SYONO, KOUKB, PLTCD, DENKB, SYUSIJNO, DENNO, SYUYTIDT, ODNDT,
NOUYTIDT, HAITM, QUNSID, TYAKBKB, COOLKB, TIMESKB, QKOGSU, TOKCD, NHSCD, LINNO,
SYUSIJLINNO, OKRJNO, HINCD, SOUCD, LOTID, TORSU, STSFL, ERRNO, ERRCM, OPEID, CLTID, WRTTM, WRTDT
FROM NSY_USR1.SJSWRA
')
;

--ビュー：o_SOUMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.SOUMTA
CREATE OR ALTER VIEW o_SOUMTA AS
SELECT
DATKB, SOUCD, SOUNM, SOUBMNCD, KTNCD, LOCTRAKB, LOCTRBKB,
RELFL, MONTNADT, MONTNBDT, TNAFLA, TNAFLB, TNAFLC, OPEID, CLTID, WRTTM, WRTDT,
UPDCNTNO, TRNNO, SOUNMA, MPDMSTKB, TOKCD, NHSCD
FROM OPENQUERY(ORCL,
'
SELECT
DATKB, SOUCD, SOUNM, SOUBMNCD, KTNCD, LOCTRAKB, LOCTRBKB,
RELFL, MONTNADT, MONTNBDT, TNAFLA, TNAFLB, TNAFLC, OPEID, CLTID, WRTTM, WRTDT,
UPDCNTNO, TRNNO, SOUNMA, MPDMSTKB, TOKCD, NHSCD
FROM NSY_USR1.SOUMTA
WHERE DATKB = ''1''
')
;

--ビュー：o_SSZTRA
--FROM: [ORCL-LINK].ORCLLINK.dbo.SSZTRA
CREATE OR ALTER VIEW o_SSZTRA AS
SELECT
DKBSB, DATNO, DATKB, DENKB, DENNO, LINNO, SOUCD, SYUSIJKB, SYUSIJNO, SYUSIJLINNO, ADNID, SYUYTIDT, NOUYTIDT, TOKCD, TOKRN, TOKZP, TOKADA,
TOKADB, TOKADC, TOKTL, TOKFX, NHSCD, HSSRN, HSSZP, HSSADA, HSSADB, HSSADC, HSSTL, QUNSID, DENCMC, HINCD, HINNMA, HINNMB, SEIHINNMA,
SEIHINNMB, HINNMMKB, COMHINCD, LOTID, LCTDT, OTPSU, IYAKUKB, OPEID, CLTID, WRTTM, WRTDT, CRTTM, CRTDT, LOTAID, LOTBID, HAKKB, KOUKB, CRFKB,
NHSNMA, NHSNMB, DENCM, TORSU
FROM OPENQUERY(ORCL,
'
SELECT
DKBSB, DATNO, DATKB, DENKB, DENNO, LINNO, SOUCD, SYUSIJKB, SYUSIJNO, SYUSIJLINNO, ADNID, SYUYTIDT, NOUYTIDT, TOKCD, TOKRN, TOKZP, TOKADA,
TOKADB, TOKADC, TOKTL, TOKFX, NHSCD, HSSRN, HSSZP, HSSADA, HSSADB, HSSADC, HSSTL, QUNSID, DENCMC, HINCD, HINNMA, HINNMB, SEIHINNMA,
SEIHINNMB, HINNMMKB, COMHINCD, LOTID, LCTDT, OTPSU, IYAKUKB, OPEID, CLTID, WRTTM, WRTDT, CRTTM, CRTDT, LOTAID, LOTBID, HAKKB, KOUKB, CRFKB,
NHSNMA, NHSNMB, DENCM, TORSU
FROM NSY_USR1.SSZTRA
where DATKB = ''1''
')
;

--ビュー：o_STGTRA
--FROM: [ORCL-LINK].ORCLLINK.dbo.STGTRA
CREATE OR ALTER VIEW o_STGTRA AS
SELECT
DATNO, PDNNO, LINNO, PDNDT, SIRSHACD, SIRBMNCD, BNKCD, TEGDT, TEGNO, TEGKN, LINCMA, LINCMB, OPEID, CLTID, WRTTM, WRTDT
FROM OPENQUERY(ORCL,
'
SELECT DATNO, PDNNO, LINNO, PDNDT, SIRSHACD, SIRBMNCD, BNKCD, TEGDT, TEGNO, TEGKN, LINCMA, LINCMB, OPEID, CLTID, WRTTM, WRTDT FROM NSY_USR1.STGTRA
')
;

--ビュー：o_SYSTBD
--FROM: [ORCL-LINK].ORCLLINK.dbo.SYSTBD
CREATE OR ALTER VIEW o_SYSTBD AS
SELECT
DKBSB, DKBID, DKBNMB, DKBNM, UPDID, DFLDKBCD, DKBZAIFL, DKBTEGFL, DKBFLA, DKBFLB, DKBFLC, MHJSQ, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM OPENQUERY(ORCL,
'
SELECT
DKBSB, DKBID, DKBNMB, DKBNM, UPDID, DFLDKBCD, DKBZAIFL, DKBTEGFL, DKBFLA, DKBFLB, DKBFLC, MHJSQ, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM NSY_USR1.SYSTBD
')
;

--ビュー：o_TANMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.TANMTA
CREATE OR ALTER VIEW o_TANMTA AS
SELECT
DATKB, TANMSTKB, TANCD, TANNM, TANNK, TANCLAKB, TANCLBKB, TANCLCKB, TANCLAID, TANCLBID, TANCLCID, TANBMNCD, RELFL, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM OPENQUERY(ORCL,
'
SELECT
DATKB, TANMSTKB, TANCD, TANNM, TANNK, TANCLAKB, TANCLBKB, TANCLCKB, TANCLAID, TANCLBID, TANCLCID, TANBMNCD, RELFL, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM NSY_USR1.TANMTA
WHERE DATKB = ''1''
')
;

--ビュー：o_TOKMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.TOKMTA
CREATE OR ALTER VIEW o_TOKMTA AS
SELECT
DATKB, TOKMSTKB, TOKCD, TOKNMA, TOKNMB, TOKRN, TOKNK, TOKZP, TOKADA, TOKADB, TOKADC, TOKTL, TOKFX, TOKBOSNM, TOKTANNM, TOKCLAKB, TOKCLBKB,
TOKCLCKB, TOKCLAID, TOKCLBID, TOKCLCID, TANCD, TOKBMNCD, URKZANDT, URKZANKN, SEIZANDT, SEIZANKN, SMAZANDT, SMAZANKN, SSAZANDT, SSAZANKN,
LSTTORDT, TOKSMEKB, TOKSMEDD, TOKSMECC, TOKSDWKB, TOSKIJFL, TOKKESDD, TOKKESCC, TOKKDWKB, MMNGNKKN, MMNGNKKB, IJYKESKB00, IJYKESKB01,
IJYKESKB02, IJYKESKB03, IJYKESKB04, IJYKESRT00, IJYKESRT01, IJYKESRT02, IJYKESRT03, IJYKESRT04, UKETEGST00, UKETEGST01, UKETEGST02, UKETEGST03, UKETEGST04,
FIXGNKKN, KESFKMFL, UTGYSOFL, KESFL, TOKZEIKB, TOKZCLKB, TOKRPSKB, TOKZRNKB, TOKSEICD, SEIPRYKB, LMTKN, TNKKB, TOKTKSID, UTKKRHKB, UKNKRHKB,
TOKNMMKB, TOKNKDKB, TOKSUMCD, TOKJUNKB, EOSMISID, EOSTORID, KEITOKCD, LSTID, SKDUYSKB, NEGKB, HANLSTCD, SEALSTCD, SEBLSTCD, RELFL, RUNSSADT,
RUNSSBDT, RUNCHGKB, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, ESTLSTCD, HANBOSCD, SEBBOSCD, SEABOSCD, ESTBOSCD, HANPRIKB, SEBPRIKB,
SEAPRIKB, ESTPRIKB, GYOCD, HOSCD, MEMOA, MEMOB, MEMOC, MEMOD, MEMOE, MEMOF, MEMOG, MEMOH, MEMOI, MEMOJ, MPDMSTKB, RUNSSCDT, TOKHIKTM,
SMESSADT, SMESSBDT, SMESSCDT, SMESSDDT, KACD, KKRCD, TOKSIKKB, TOKCLKB, BYOKEIKB, BYOZAIKB, TOKDAICD, YSNCD, GYOSYUCD, GYOTAICD, KGSCD,
DOKHANKB, DOUHANKB, DOKHANDT, DOUHANDT, TEKHYOKB, BYOSYOSU, TOKSEINMA, TOKSEINMB, TOKSEIZP, TOKSEIADA, TOKSEIADB, TOKSEIADC, SOUCD,
KESDD, KESCMA, KESCMB, TKMKB, PLNKB, PLNKOZKB, SPDRELKB, JOTOKB, INTNHSCD, JDORSCD, JDORSSCD, HOSTAIKB, HOSCLCKB, HOSSTAKB, HOSCLCRT,
HOSCLCKN, HOSSKETKB, HOSHASKB, NEBPRNKB, UDNFIXDT, TANMAILAD, JDSKKB, JSOLSKKB, PRSKKB, TNHTMCD, MDIRYOCD, SDMOTOCD, CMMOTOCD, MDSIKKB,
SDSIKKB, SDHINKB, MDNFRMKB, GTMOTOCD, GTSIKKB, GTHINKB
FROM OPENQUERY(ORCL,
'
SELECT
DATKB, TOKMSTKB, TOKCD, TOKNMA, TOKNMB, TOKRN, TOKNK, TOKZP, TOKADA, TOKADB, TOKADC, TOKTL, TOKFX, TOKBOSNM, TOKTANNM, TOKCLAKB, TOKCLBKB,
TOKCLCKB, TOKCLAID, TOKCLBID, TOKCLCID, TANCD, TOKBMNCD, URKZANDT, URKZANKN, SEIZANDT, SEIZANKN, SMAZANDT, SMAZANKN, SSAZANDT, SSAZANKN,
LSTTORDT, TOKSMEKB, TOKSMEDD, TOKSMECC, TOKSDWKB, TOSKIJFL, TOKKESDD, TOKKESCC, TOKKDWKB, MMNGNKKN, MMNGNKKB, IJYKESKB00, IJYKESKB01,
IJYKESKB02, IJYKESKB03, IJYKESKB04, IJYKESRT00, IJYKESRT01, IJYKESRT02, IJYKESRT03, IJYKESRT04, UKETEGST00, UKETEGST01, UKETEGST02, UKETEGST03, UKETEGST04,
FIXGNKKN, KESFKMFL, UTGYSOFL, KESFL, TOKZEIKB, TOKZCLKB, TOKRPSKB, TOKZRNKB, TOKSEICD, SEIPRYKB, LMTKN, TNKKB, TOKTKSID, UTKKRHKB, UKNKRHKB,
TOKNMMKB, TOKNKDKB, TOKSUMCD, TOKJUNKB, EOSMISID, EOSTORID, KEITOKCD, LSTID, SKDUYSKB, NEGKB, HANLSTCD, SEALSTCD, SEBLSTCD, RELFL, RUNSSADT,
RUNSSBDT, RUNCHGKB, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, ESTLSTCD, HANBOSCD, SEBBOSCD, SEABOSCD, ESTBOSCD, HANPRIKB, SEBPRIKB,
SEAPRIKB, ESTPRIKB, GYOCD, HOSCD, MEMOA, MEMOB, MEMOC, MEMOD, MEMOE, MEMOF, MEMOG, MEMOH, MEMOI, MEMOJ, MPDMSTKB, RUNSSCDT, TOKHIKTM,
SMESSADT, SMESSBDT, SMESSCDT, SMESSDDT, KACD, KKRCD, TOKSIKKB, TOKCLKB, BYOKEIKB, BYOZAIKB, TOKDAICD, YSNCD, GYOSYUCD, GYOTAICD, KGSCD,
DOKHANKB, DOUHANKB, DOKHANDT, DOUHANDT, TEKHYOKB, BYOSYOSU, TOKSEINMA, TOKSEINMB, TOKSEIZP, TOKSEIADA, TOKSEIADB, TOKSEIADC, SOUCD,
KESDD, KESCMA, KESCMB, TKMKB, PLNKB, PLNKOZKB, SPDRELKB, JOTOKB, INTNHSCD, JDORSCD, JDORSSCD, HOSTAIKB, HOSCLCKB, HOSSTAKB, HOSCLCRT,
HOSCLCKN, HOSSKETKB, HOSHASKB, NEBPRNKB, UDNFIXDT, TANMAILAD, JDSKKB, JSOLSKKB, PRSKKB, TNHTMCD, MDIRYOCD, SDMOTOCD, CMMOTOCD, MDSIKKB,
SDSIKKB, SDHINKB, MDNFRMKB, GTMOTOCD, GTSIKKB, GTHINKB
FROM NSY_USR1.TOKMTA
')
;

--ビュー：o_TOKMTB
--FROM: [ORCL-LINK].ORCLLINK.dbo.TOKMTB
CREATE OR ALTER VIEW o_TOKMTB AS
SELECT
DATKB, TOKCD, HINCD, URITKDT00, URITKDT01, URITKDT02, URITKDT03, URITKDT04, URITKDT05, UDNNO00, UDNNO01, UDNNO02, UDNNO03, UDNNO04, UDNNO05,
UDNDT00, UDNDT01, UDNDT02, UDNDT03, UDNDT04, UDNDT05, UNTIN00, UNTIN01, UNTIN02, UNTIN03, UNTIN04, UNTIN05, UNTNM00, UNTNM01, UNTNM02,
UNTNM03, UNTNM04, UNTNM05, IRISU00, IRISU01, IRISU02, IRISU03, IRISU04, IRISU05, HISURITK00, HISURITK01, HISURITK02, HISURITK03, HISURITK04, HISURITK05,
AZUZANDT, AZUZANSU, AZUZANKN, EOSHINID, OPEID, CLTID, WRTTM, WRTDT, HISGNKTK00, HISGNKTK01, HISGNKTK02, HISGNKTK03, HISGNKTK04, HISGNKTK05
FROM OPENQUERY(ORCL,
'
SELECT
DATKB, TOKCD, HINCD, URITKDT00, URITKDT01, URITKDT02, URITKDT03, URITKDT04, URITKDT05, UDNNO00, UDNNO01, UDNNO02, UDNNO03, UDNNO04, UDNNO05,
UDNDT00, UDNDT01, UDNDT02, UDNDT03, UDNDT04, UDNDT05, UNTIN00, UNTIN01, UNTIN02, UNTIN03, UNTIN04, UNTIN05, UNTNM00, UNTNM01, UNTNM02,
UNTNM03, UNTNM04, UNTNM05, IRISU00, IRISU01, IRISU02, IRISU03, IRISU04, IRISU05, HISURITK00, HISURITK01, HISURITK02, HISURITK03, HISURITK04, HISURITK05,
AZUZANDT, AZUZANSU, AZUZANKN, EOSHINID, OPEID, CLTID, WRTTM, WRTDT, HISGNKTK00, HISGNKTK01, HISGNKTK02, HISGNKTK03, HISGNKTK04, HISGNKTK05
FROM NSY_USR1.TOKMTB
')
;

--ビュー：o_TOKMTS
--FROM: [ORCL-LINK].ORCLLINK.dbo.TOKMTS
CREATE OR ALTER VIEW o_TOKMTS AS
SELECT
TOKCD, QTENCD, HINCD, UNTIN, QSPCKB, QENDDT, QSTADT,
URITKADT, URITK, QDGENTK, QDBAITK, QRBTHTK, QRBTHRT,
OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, NEBTK, XRNNO
FROM OPENQUERY(ORCL,
'
SELECT
TOKCD, QTENCD, HINCD, UNTIN, QSPCKB, QENDDT, QSTADT,
URITKADT, URITK, QDGENTK, QDBAITK, QRBTHTK, QRBTHRT,
OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, NEBTK, XRNNO
FROM NSY_USR1.TOKMTS
')
;

--ビュー：o_TOKMTV
--FROM: [ORCL-LINK].ORCLLINK.dbo.TOKMTV
CREATE OR ALTER VIEW o_TOKMTV AS
SELECT
TOKCD, HINCD, LOTBAKKB, HIKSYRKB, LINCMCD00, LINCMCD01, LINCM00, LINCM01, LSTKIGDT, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM OPENQUERY(ORCL,
'
SELECT
TOKCD, HINCD, LOTBAKKB, HIKSYRKB, LINCMCD00, LINCMCD01, LINCM00, LINCM01, LSTKIGDT, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM NSY_USR1.TOKMTV
')
;

--ビュー：o_TOKSSA
--FROM: [ORCL-LINK].ORCLLINK.dbo.TOKSSA
CREATE OR ALTER VIEW o_TOKSSA AS
SELECT
TOKCD, SSADT, KESDT, SSAURIKN00, SSAURIKN01, SSAURIKN02, SSAURIKN03, SSAURIKN04, SSAURIKN05, SSAURIKN06, SSAURIKN07, SSAURIKN08, SSAURIKN09,
SSAUZEKN, SSAUZKKN, SSANYUKN00, SSANYUKN01, SSANYUKN02, SSANYUKN03, SSANYUKN04, SSANYUKN05, SSANYUKN06, SSANYUKN07, SSANYUKN08, SSANYUKN09,
SSADENSU, SSACURKN00, SSACURKN01, SSACURKN02, SSACURKN03, SSACURKN04, SSACURKN05, SSACURKN06, SSACURKN07, SSACURKN08, SSACURKN09,
SSACUZKN, SSACUKKN, SZAKZIKN00, SZAKZIKN01, SZAKZIKN02, SZBKZIKN00, SZBKZIKN01, SZBKZIKN02, DATNO, SSARIZKN, WRTTM, WRTDT, SSADELKN
FROM OPENQUERY(ORCL,
'
SELECT
TOKCD, SSADT, KESDT, SSAURIKN00, SSAURIKN01, SSAURIKN02, SSAURIKN03, SSAURIKN04, SSAURIKN05, SSAURIKN06, SSAURIKN07, SSAURIKN08, SSAURIKN09,
SSAUZEKN, SSAUZKKN, SSANYUKN00, SSANYUKN01, SSANYUKN02, SSANYUKN03, SSANYUKN04, SSANYUKN05, SSANYUKN06, SSANYUKN07, SSANYUKN08, SSANYUKN09,
SSADENSU, SSACURKN00, SSACURKN01, SSACURKN02, SSACURKN03, SSACURKN04, SSACURKN05, SSACURKN06, SSACURKN07, SSACURKN08, SSACURKN09,
SSACUZKN, SSACUKKN, SZAKZIKN00, SZAKZIKN01, SZAKZIKN02, SZBKZIKN00, SZBKZIKN01, SZBKZIKN02, DATNO, SSARIZKN, WRTTM, WRTDT, SSADELKN
FROM NSY_USR1.TOKSSA
')
;

--ビュー：o_UDNTHA
--FROM: [ORCL-LINK].ORCLLINK.dbo.UDNTHA
CREATE OR ALTER VIEW o_UDNTHA AS
SELECT
*
FROM OPENQUERY(ORCL,
'
select
*
from NSY_USR1.UDNTHA
WHERE DATKB = ''1''
')
;
/*いる行:
DATNO,DATKB,DENKB,UDNNO,JDNNO,UDNDT,SMADT,NXTKB,SSADT,KESDT,TOKCD,TOKRN,NHSCD,NHSRN,TOKSEICD,TANCD,SOUCD,TANBMNCD,TOKBMNCD,SOUBMNCD,SBAURIKN,SBAUZEKN,SBAUZKKN,SBANYUKN,DENCM
,TOKSMEKB,TOKSMEDD,TOKSMECC,TOKKESDD,TOKKESCC,TOKZEIKB,TOKZCLKB,TOKRPSKB,TOKZRNKB,TOKNMMKB,NHSNMMKB,ADNID,LSTID,TOKMSTKB,NHSMSTKB,TANMSTKB,NHSKB,UPFKB,CSHKB,DHAKB,HANLSTCD
,DKBSB,TOKNKDKB,OPEID,CLTID,WRTTM,WRTDT,CRTTM,CRTDT,UPDCNTNO,TRNNO,JHDCNTNO,OIDCNTNO,JDNSMEKB,HANHAKKB,SEAHAKKB,SEBHAKKB,ESTHAKKB,TOKCLAKB,TOKCLBKB,TOKCLCKB,TOKCLAID,TOKCLBID
,UHAKB,SBAGNKKN,SYUHAKKB,DEFCRTTM,DEFCRTDT,KRDKB,JUCKB,NHNDT,OKRJNO,HSSRN,HSSZP,HSSADA,HSSADB,HSSADC,HSSTL,HSSFX,MUDNNO,CSVCRDT,WMSKB,QUNSID
*/

--ビュー：o_UDNTRA
--FROM: [ORCL-LINK].ORCLLINK.dbo.UDNTRA
CREATE OR ALTER VIEW o_UDNTRA AS
SELECT
*
FROM OPENQUERY(ORCL,
'
select
*
from NSY_USR1.UDNTRA
WHERE DATKB = ''1''
')
;
/*いる行:
DATNO,DATKB,DENKB,UDNNO,LINNO,JDNNO,JDNLINNO,RECNO,ODNRECNO,UDNDT,SMADT,SSADT,KESDT,TOKCD,NHSCD,TOKSEICD,TANCD,SOUCD,TANBMNCD,TOKBMNCD,SOUBMNCD,HINCD,HINNMA,HINNMB,MAKCD,HINSIRCD,HINNMMKB,HINKB,ZAIKB,MRPKB,COLCD,UNTCD,UNTIN,UNTNM,IRISU,
CASSU,URISU,URITK,GNKTK,URIKN,UZEKN,ZKMUZEKN,ZNKURIKN,GNKKN,NYUKN,LINCMA,LINCMB,UODDELSU,HINZEIKB,ZEIRNKKB,ZEIRT,LSTID,TOKMSTKB,NHSMSTKB,TANMSTKB,HINMSTKB,NHSKB,DKBSB,DKBID,DKBNM,UPDID,MHJSQ,DKBTEGFL,DKBZAIFL,ARGGSGTK,ARGGSGKN,OPEID,
CLTID,WRTTM,WRTDT,CRTTM,CRTDT,SPDDENNO,SPDLINNO,SPDEDANO,TKMCDA,TKMCDB,TKMCDC,DELSSADT,NHSTOKCD,TOKDAICD,MEICD,TKMKB,TKMNM,SPDDENKB,SPDDATKB,SPDTRIKB,SEIHINNMA,SEIHINNMB,OTPUNTSU,SPDATK,DWHKB,SYUSIJNO,NYUZEIKN,HSTSKB
*/

--ビュー：o_UNSMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.UNSMTA
CREATE OR ALTER VIEW o_UNSMTA AS
SELECT
DATKB, QUNSID, QUNSNM, QUNSNK, QUNSKKB, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, JSYHAIKB, TYAKBKB, COOLKB, TIMESKB, BITIKUKB, OUTKB, OUTDT, HAITM
FROM OPENQUERY(ORCL,
'
SELECT
DATKB, QUNSID, QUNSNM, QUNSNK, QUNSKKB, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, JSYHAIKB, TYAKBKB, COOLKB, TIMESKB, BITIKUKB, OUTKB, OUTDT, HAITM
FROM NSY_USR1.UNSMTA
WHERE DATKB = ''1''
')
;

--ビュー：o_UTGTRA
--FROM: [ORCL-LINK].ORCLLINK.dbo.UTGTRA
CREATE OR ALTER VIEW o_UTGTRA AS
SELECT
DATNO, NDNNO, LINNO, NDNDT, TOKSEICD, TOKBMNCD, BNKCD, TEGDT, TEGNO, TEGKN, LINCMA, LINCMB, OPEID, CLTID, WRTTM, WRTDT
FROM OPENQUERY(ORCL,
'
SELECT
DATNO, NDNNO, LINNO, NDNDT, TOKSEICD, TOKBMNCD, BNKCD, TEGDT, TEGNO, TEGKN, LINCMA, LINCMB, OPEID, CLTID, WRTTM, WRTDT
FROM NSY_USR1.UTGTRA
')
;

--ビュー：o_ZSGWRA
--FROM: [ORCL-LINK].ORCLLINK.dbo.ZSGWRA
CREATE OR ALTER VIEW o_ZSGWRA AS
SELECT
TNADT, SOUCD, SOUNM, HINCD, HINNMA, HINNMB, LOTID, RELZAISU, LOTLOTID, ZAISU, SRYKB, OPEID, CLTID, WRTTM, WRTDT
FROM OPENQUERY(ORCL,
'
SELECT
TNADT, SOUCD, SOUNM, HINCD, HINNMA, HINNMB, LOTID, RELZAISU, LOTLOTID, ZAISU, SRYKB, OPEID, CLTID, WRTTM, WRTDT
FROM NSY_USR1.ZSGWRA
')
;


/*m_テーブル*/

--ビュー名：m_カクテル取引先県マスタ
--FROM: dbo.o_CLSMTA
CREATE OR ALTER VIEW m_カクテル取引先県マスタ as
select
    RTRIM(CLSID) as 県コード
    ,RTRIM(CLSNM) as 県名
from dbo.o_CLSMTA
where CLSKB='0'
;

--ビュー名：m_カクテル商品科目分類マスタ
--FROM: dbo.o_MEIMTA
CREATE OR ALTER VIEW m_カクテル商品科目分類マスタ as
select
    TOP(100) percent
    RTRIM(MEICD) as 科目分類コード
    ,RTRIM(MEINM) as 科目分類名
    ,RTRIM(MEIRN) as 科目分類略称
from dbo.o_MEIMTA
where MEISB = '02'
order by 科目分類コード
;

--ビュー名：m_カクテル商品規制区分マスタ
--FROM: dbo.o_MEIMTA
CREATE OR ALTER VIEW m_カクテル商品規制区分マスタ as
select
    TOP(100) percent
    RTRIM(MEICD) as 規制分類コード
    ,RTRIM(MEINM) as 規制分類名
    ,RTRIM(MEIRN) as 規制分類略称
from dbo.o_MEIMTA
where MEISB = '83'
order by 規制分類コード
;

--ビュー名：m_カクテル商品区分マスタ
--FROM: dbo.o_CLSMTA
CREATE OR ALTER VIEW m_カクテル商品区分マスタ AS
select
    TOP(100) percent
    RTRIM(CLSID) as 商品区分コード
    ,RTRIM(CLSNM) as 商品区分名
from dbo.o_CLSMTA
where CLSKB='7'
order by 商品区分コード
;

--ビュー名：m_カクテル商品剤型区分マスタ
--FROM: dbo.o_CLSMTA
CREATE OR ALTER VIEW m_カクテル商品剤型区分マスタ AS
select
    TOP(100) percent
    RTRIM(CLSID) as 剤型区分コード
    ,RTRIM(CLSNM) as 剤型区分名
from dbo.o_CLSMTA
where CLSKB='8'
order by 剤型区分コード
;

--ビュー名：m_カクテル商品受注分類マスタ
--FROM: dbo.o_MEIMTA
CREATE OR ALTER VIEW m_カクテル商品受注分類マスタ AS
select
    RTRIM(MEICD) as 受注分類コード
    ,RTRIM(MEINM) as 受注分類名
    ,RTRIM(MEIRN) as 受注分類略称
from dbo.o_MEIMTA
where MEISB='81'
;

--ビュー名：m_カクテル商品単価ランクマスタ
--FROM: dbo.o_MEIMTA
CREATE OR ALTER VIEW m_カクテル商品単価ランクマスタ AS
select
    TOP(100) percent
    RTRIM(MEICD) as 単価ランク区分コード
    ,RTRIM(MEINM) as 単価ランク名
    ,RTRIM(MEIRN) as 単価ランク略称
from dbo.o_MEIMTA
where MEISB='01'
order by 単価ランク区分コード
;

--ビュー名：m_カクテル商品薬効区分マスタ
--FROM: dbo.o_CLSMTA
CREATE OR ALTER VIEW m_カクテル商品薬効区分マスタ as
select
    TOP(100) percent
    RTRIM(CLSID) as 薬効区分コード
    ,RTRIM(CLSNM) as 薬効区分名
from dbo.o_CLSMTA
where CLSKB = '9'
order by 薬効区分コード
;

--ビュー名：m_カクテル部門マスタ
--FROM: dbo.o_BMNMTA
CREATE OR ALTER VIEW m_カクテル部門マスタ AS
select
    RTRIM(BMNCD) as 部門コード
    ,RTRIM(BMNNM) as 部門名
    ,RTRIM(BMNNK) as 部門カナ
    ,RTRIM(BMNZP) as 部門郵便番号
    ,RTRIM(BMNADA) as 部門住所1
    ,RTRIM(BMNADB) as 部門住所2
    ,RTRIM(BMNADC) AS 部門住所3
    ,RTRIM(BMNTL) AS 部門電話番号
    ,RTRIM(BMNFX) AS 部門FAX番号
from dbo.o_BMNMTA
;

--ビュー名：m_取引先得意先種別マスタ
--FROM: dbo.o_CLSMTA
CREATE OR ALTER VIEW m_取引先得意先種別マスタ as
SELECT
    TOP (100) PERCENT
    RTRIM(CLSID) AS 得意先種別コード
    ,RTRIM(CLSNM) AS 得意先種別名
from dbo.o_CLSMTA
where (CLSKB = '1')
order by 得意先種別コード
;


/* v_ビュー */


--ビュー名：v_HINMTA
--FROM: dbo.o_HINMTA
/* o_HINMTAの中身を書き換えるので変更しない */

--ビュー名：v_HINMTA_Trim
--FROM: dbo.o_HINMTA
/* o_HINMTAの中身を書き換えるので変更しない */

--ビュー名：v_HINMTC
--FROM: dbo.o_HINMTC
/* o_HINMTCの中身を書き換えるので変更しない */

--ビュー名：v_IDNTRA_SEIS
--FROM: [ORCL-LINK].ORCLLINK.dbo.v_IDNTRA_SEIS
CREATE OR ALTER VIEW v_IDNTRA_SEIS AS
    SELECT
    DATNO, DATKB, DENKB, IDNNO, LINNO, HDNNO, HDNLINNO, RECNO, IDNRECNO, IDNDT, SMADT, SIRCD, TANCD, KTNCD, SOUCD, TANBMNCD, SOUBMNCD, HINCD, HINNMA,
    HINNMB, MAKCD, HINSIRCD, HINNMMKB, HINKB, ZAIKB, MRPKB, HRTDD, ORTDD, SIZCD, COLCD, UNTCD00, UNTCD01, UNTCD02, UNTNM00, UNTNM01, UNTNM02,
    IRISU00, IRISU01, IRISU02, CASSU00, CASSU01, CASSU02, INPSU, SRESU, LINCMA, LINCMB, HATDELSU, LSTID, SIRMSTKB, TANMSTKB, HINMSTKB, DKBSB,
    DKBID, DKBNM, UPDID, MHJSQ, DKBZAIFL, NSZHYJKB, LOTKB, HINLCDKB, SUBDSPKB, HEDLOTID, HEDLCTDT, DSPUNTCD, DSPUNTIN, DSPUNTNM, DSPIRISU,
    DSPCASSU, DKBFLA, DKBFLB, DKBFLC, DFLDKBCD, OPEID, CLTID, WRTTM, WRTDT, TOKCD, SIRTNKKB, MPDSEQNO, ODNNO, DWHKB, LOTAID, LOTBID, NYUYOTNO
    FROM OPENQUERY(ORCL,
    '
    SELECT
    DATNO, DATKB, DENKB, IDNNO, LINNO, HDNNO, HDNLINNO, RECNO, IDNRECNO, IDNDT, SMADT, SIRCD, TANCD, KTNCD, SOUCD, TANBMNCD, SOUBMNCD, HINCD, HINNMA,
    HINNMB, MAKCD, HINSIRCD, HINNMMKB, HINKB, ZAIKB, MRPKB, HRTDD, ORTDD, SIZCD, COLCD, UNTCD00, UNTCD01, UNTCD02, UNTNM00, UNTNM01, UNTNM02,
    IRISU00, IRISU01, IRISU02, CASSU00, CASSU01, CASSU02, INPSU, SRESU, LINCMA, LINCMB, HATDELSU, LSTID, SIRMSTKB, TANMSTKB, HINMSTKB, DKBSB,
    DKBID, DKBNM, UPDID, MHJSQ, DKBZAIFL, NSZHYJKB, LOTKB, HINLCDKB, SUBDSPKB, HEDLOTID, HEDLCTDT, DSPUNTCD, DSPUNTIN, DSPUNTNM, DSPIRISU,
    DSPCASSU, DKBFLA, DKBFLB, DKBFLC, DFLDKBCD, OPEID, CLTID, WRTTM, WRTDT, TOKCD, SIRTNKKB, MPDSEQNO, ODNNO, DWHKB, LOTAID, LOTBID, NYUYOTNO
    FROM NSY_USR1.v_IDNTRA_SEIS
    ')
;

--ビュー名：v_IDNTRA_SEIS2
--FROM: [ORCL-LINK].ORCLLINK.dbo.v_IDNTRA_SEIS2
CREATE OR ALTER VIEW v_IDNTRA_SEIS2 AS
    SELECT
    DATNO, DATKB, DENKB, IDNNO, LINNO, HDNNO, HDNLINNO, RECNO, IDNRECNO, IDNDT, SMADT, SIRCD, TANCD, KTNCD, SOUCD, TANBMNCD, SOUBMNCD,
    HINCD, HINNMA, HINNMB, MAKCD, HINSIRCD, HINNMMKB, HINKB, ZAIKB, MRPKB, HRTDD, ORTDD, SIZCD, COLCD, UNTCD00, UNTCD01, UNTCD02, UNTNM00,
    UNTNM01, UNTNM02, IRISU00, IRISU01, IRISU02, CASSU00, CASSU01, CASSU02, INPSU, SRESU, LINCMA, LINCMB, HATDELSU, LSTID, SIRMSTKB, TANMSTKB,
    HINMSTKB, DKBSB, DKBID, DKBNM, UPDID, MHJSQ, DKBZAIFL, NSZHYJKB, LOTKB, HINLCDKB, SUBDSPKB, HEDLOTID, HEDLCTDT, DSPUNTCD, DSPUNTIN, DSPUNTNM,
    DSPIRISU, DSPCASSU, DKBFLA, DKBFLB, DKBFLC, DFLDKBCD, OPEID, CLTID, WRTTM, WRTDT, TOKCD, SIRTNKKB, MPDSEQNO, ODNNO, DWHKB, LOTAID, LOTBID, NYUYOTNO
    FROM OPENQUERY(ORCL,
    '
    SELECT
    DATNO, DATKB, DENKB, IDNNO, LINNO, HDNNO, HDNLINNO, RECNO, IDNRECNO, IDNDT, SMADT, SIRCD, TANCD, KTNCD, SOUCD, TANBMNCD, SOUBMNCD,
    HINCD, HINNMA, HINNMB, MAKCD, HINSIRCD, HINNMMKB, HINKB, ZAIKB, MRPKB, HRTDD, ORTDD, SIZCD, COLCD, UNTCD00, UNTCD01, UNTCD02, UNTNM00,
    UNTNM01, UNTNM02, IRISU00, IRISU01, IRISU02, CASSU00, CASSU01, CASSU02, INPSU, SRESU, LINCMA, LINCMB, HATDELSU, LSTID, SIRMSTKB, TANMSTKB,
    HINMSTKB, DKBSB, DKBID, DKBNM, UPDID, MHJSQ, DKBZAIFL, NSZHYJKB, LOTKB, HINLCDKB, SUBDSPKB, HEDLOTID, HEDLCTDT, DSPUNTCD, DSPUNTIN, DSPUNTNM,
    DSPIRISU, DSPCASSU, DKBFLA, DKBFLB, DKBFLC, DFLDKBCD, OPEID, CLTID, WRTTM, WRTDT, TOKCD, SIRTNKKB, MPDSEQNO, ODNNO, DWHKB, LOTAID, LOTBID, NYUYOTNO
    FROM NSY_USR1.v_IDNTRA_SEIS2
    ')
;

--ビュー名：v_JDNTHA
--FROM: dbo.o_JDNTHA
/* o_JDNTHAの中身を書き換えるので変更しない */

--ビュー名：v_JDNTHA_2M
--FROM: [ORCL-LINK].ORCLLINK.dbo.v_JDNTHA_2M
CREATE OR ALTER VIEW v_JDNTHA_2M AS
    SELECT
    DATKB, DENKB, JDNNO, JDNDT, DEFNOKDT, JUCSYYDT, SMADT, TOKCD, TOKRN, NHSCD, NHSRN, TOKSEICD, TANCD, KTNCD, SOUCD, TANBMNCD, TOKBMNCD,
    SOUBMNCD, SBAUODKN, SBAJZEKN, SBAJZKKN, SYUBACID, ROTCD, ROTSHPSQ, DENCM, DENCMB, TOKSMEKB, TOKSMEDD, TOKSMECC, TOKSDWKB, TOKKESDD,
    TOKKESCC, TOKKDWKB, TOKZEIKB, TOKZCLKB, TOKRPSKB, TOKZRNKB, TOKNMMKB, NHSNMMKB, ADNID, LSTID, TOKMSTKB, NHSMSTKB, TANMSTKB, NHSKB, DKBSB,
    TOKNKDKB, JDNENDKB, ODNKB, ODNENDKB, UDNENDKB, SVCKB, SVCENDKB, URIKJNKB, LSTTORDT, MOTDATNO, OPEID, CLTID, WRTTM, WRTDT, CRTTM, CRTDT,
    UPDCNTNO, TRNNO, CSVDATNO, JHAKB, JDNSMEKB, TOKCLAKB, TOKCLBKB, TOKCLCKB, TOKCLAID, TOKCLBID, TOKCLCID, PIKHAKKB, SBAGNKKN, ALSKB, KRDKB,
    JUCKB, HSSRN, HSSZP, HSSADA, HSSADB, HSSADC, HSSTL, HSSFX, DENCMBCD, DENCMCCD, DENCMC, QUNSID, NXTKB, DATNO
    FROM OPENQUERY(ORCL,
    '
    SELECT
    DATKB, DENKB, JDNNO, JDNDT, DEFNOKDT, JUCSYYDT, SMADT, TOKCD, TOKRN, NHSCD, NHSRN, TOKSEICD, TANCD, KTNCD, SOUCD, TANBMNCD, TOKBMNCD,
    SOUBMNCD, SBAUODKN, SBAJZEKN, SBAJZKKN, SYUBACID, ROTCD, ROTSHPSQ, DENCM, DENCMB, TOKSMEKB, TOKSMEDD, TOKSMECC, TOKSDWKB, TOKKESDD,
    TOKKESCC, TOKKDWKB, TOKZEIKB, TOKZCLKB, TOKRPSKB, TOKZRNKB, TOKNMMKB, NHSNMMKB, ADNID, LSTID, TOKMSTKB, NHSMSTKB, TANMSTKB, NHSKB, DKBSB,
    TOKNKDKB, JDNENDKB, ODNKB, ODNENDKB, UDNENDKB, SVCKB, SVCENDKB, URIKJNKB, LSTTORDT, MOTDATNO, OPEID, CLTID, WRTTM, WRTDT, CRTTM, CRTDT,
    UPDCNTNO, TRNNO, CSVDATNO, JHAKB, JDNSMEKB, TOKCLAKB, TOKCLBKB, TOKCLCKB, TOKCLAID, TOKCLBID, TOKCLCID, PIKHAKKB, SBAGNKKN, ALSKB, KRDKB,
    JUCKB, HSSRN, HSSZP, HSSADA, HSSADB, HSSADC, HSSTL, HSSFX, DENCMBCD, DENCMCCD, DENCMC, QUNSID, NXTKB, DATNO
    FROM NSY_USR1.v_JDNTHA_2M
    WHERE DATKB = ''1''
    ')
;
