/**
2024.07.01 y.takeda
説明：120.6(SQL Server)の各種伝票ビューを120.12(Oracle)を直接参照する形式に変更する
DB: 192.168.120.6 > cocktail > ビュー
*/

/*m_テーブル*/

--ビュー名：m_カクテル取引先県マスタ
--FROM: dbo.o_CLSMTA
CREATE OR ALTER m_カクテル取引先県マスタ as
select
    RTRIM(CLSID) as 県コード
    ,RTRIM(CLSNM) as 県名
from dbo.o_CLSMTA
where CLSKB='0'
;

--ビュー名：m_カクテル商品科目分類マスタ
--FROM: dbo.o_MEIMTA
CREATE OR ALTER m_カクテル商品科目分類マスタ as
select
    TOP(100) percent
    RTRIM(MEICD) as 科目分類コード
    ,RTRIM(MEINM) as 科目分類名
    ,RTRIM(MEIRN) as 科目分類略称
from dbo.o_MEIMTA
where MEISB = '02'
order by 科目分類コード
;

--ビュー名：m_カクテル商品規制区分マスタ
--FROM: dbo.o_MEIMTA
CREATE OR ALTER m_カクテル商品規制区分マスタ as
select
    TOP(100) percent
    RTRIM(MEICD) as 規制分類コード
    ,RTRIM(MEINM) as 規制分類名
    ,RTRIM(MEIRN) as 規制分類略称
from dbo.o_MEIMTA
where MEISB = '83'
order by 規制分類コード
;

--ビュー名：m_カクテル商品区分マスタ
--FROM: dbo.o_CLSMTA
CREATE OR ALTER m_カクテル商品区分マスタ AS
select
    TOP(100) percent
    RTRIM(CLSID) as 商品区分コード
    ,RTRIM(CLSNM) as 商品区分名
from dbo.o_CLSMTA
where CLSKB='7'
order by 商品区分コード
;

--ビュー名：m_カクテル商品剤型区分マスタ
--FROM: dbo.o_CLSMTA
CREATE OR ALTER m_カクテル商品剤型区分マスタ AS
select
    TOP(100) percent
    RTRIM(CLSID) as 剤型区分コード
    ,RTRIM(CLSNM) as 剤型区分名
from dbo.o_CLSMTA
where CLSKB='8'
order by 剤型区分コード
;

--ビュー名：m_カクテル商品受注分類マスタ
--FROM: dbo.o_MEIMTA
CREATE OR ALTER m_カクテル商品受注分類マスタ AS
select
    RTRIM(MEICD) as 受注分類コード
    ,RTRIM(MEINM) as 受注分類名
    ,RTRIM(MEIRN) as 受注分類略称
from dbo.o_MEIMTA
where MEISB='81'
;

--ビュー名：m_カクテル商品単価ランクマスタ
--FROM: dbo.o_MEIMTA
CREATE OR ALTER m_カクテル商品単価ランクマスタ AS
select
    TOP(100) percent
    RTRIM(MEICD) as 単価ランク区分コード
    ,RTRIM(MEINM) as 単価ランク名
    ,RTRIM(MEIRN) as 単価ランク略称
from dbo.o_MEIMTA
where MEISB='01'
order by 単価ランク区分コード
;

--ビュー名：m_カクテル商品薬効区分マスタ
--FROM: dbo.o_CLSMTA
CREATE OR ALTER m_カクテル商品薬効区分マスタ as
select
    TOP(100) percent
    RTRIM(CLSID) as 薬効区分コード
    ,RTRIM(CLSNM) as 薬効区分名
from dbo.o_CLSMTA
where CLSKB = '9'
order by 薬効区分コード
;

--ビュー名：m_カクテル部門マスタ
--FROM: dbo.o_BMNMTA
CREATE OR ALTER m_カクテル部門マスタ AS
select
    RTRIM(BMNCD) as 部門コード
    ,RTRIM(BMNNM) as 部門名
    ,RTRIM(BMNNK) as 部門カナ
    ,RTRIM(BMNZP) as 部門郵便番号
    ,RTRIM(BMNADA) as 部門住所1
    ,RTRIM(BMNADB) as 部門住所2
    ,RTRIM(BMNADC) AS 部門住所3
    ,RTRIM(BMNTL) AS 部門電話番号
    ,RTRIM(BMNFX) AS 部門FAX番号
from dbo.o_BMNMTA
;

--ビュー名：m_取引先得意先種別マスタ
--FROM: dbo.o_CLSMTA
CREATE OR ALTER m_取引先得意先種別マスタ as
SELECT
    TOP (100) PERCENT
    RTRIM(CLSID) AS 得意先種別コード
    ,RTRIM(CLSNM) AS 得意先種別名
from dbo.o_CLSMTA
where (CLSKB = '1')
order by 得意先種別コード
;

/*o_テーブル*/

--ビュー：o_BMNMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.BMNMTA
CREATE OR ALTER o_BMNMTA AS
SELECT
DATKB, BMNMSTKB, BMNCD, BMNNM, BMNNK, BMNZP, BMNADA, BMNADB, BMNADC,BMNTL, BMNFX, BMNCLAKB, BMNCLBKB, BMNCLCKB, BMNCLAID, BMNCLBID,BMNCLCID, KEIBUMCD, RELFL, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, MPDMSTKB
FROM OPENQUERY(ORCL,
'
SELECT
DATKB, BMNMSTKB, BMNCD, BMNNM, BMNNK, BMNZP, BMNADA, BMNADB, BMNADC,BMNTL, BMNFX, BMNCLAKB, BMNCLBKB, BMNCLCKB, BMNCLAID, BMNCLBID,BMNCLCID, KEIBUMCD, RELFL, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, MPDMSTKB
FROM NSY_USR1.BMNMTA
WHERE DATKB = ''1''
')
;

--ビュー：o_BMKMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.BMKMTA
CREATE OR ALTER o_BMKMTA AS
SELECT
DATKB, BNKCD, BNKNM, BNKKMKCD00, BNKKMKCD01,KOZID00, KOZID01, RELFL, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM OPENQUERY(ORCL,
'SELECT
DATKB, BNKCD, BNKNM, BNKKMKCD00, BNKKMKCD01,KOZID00, KOZID01, RELFL, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM NSY_USR1.BNKMTA
WHERE DATKB =''1''
')
;

--ビュー：o_CLSMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.CLSMTA
CREATE OR ALTER o_CLSMTA AS
SELECT CLSKB, CLSID, CLSNM, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM OPENQUERY(ORCL,
'SELECT CLSKB, CLSID, CLSNM, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM NSY_USR1.CLSMTA
')
;

--ビュー：o_HINMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.HINMTA
CREATE OR ALTER o_HINMTA AS
SELECT
DATKB, HINMSTKB, HINCD, HINNMA, HINNMB, HINNK, HINCLAKB, HINCLBKB, HINCLCKB, HINCLAID, HINCLBID, HINCLCID, HINSIRCD, MAKCD, HINCMA,
HINCMB, HINCMC, HINCMD, HINCME, TNABTK00, TNABTK01, TNABTK02, TNABTK03, TNABTK04, TNABTK05, TNABTK06, TNABTK07, TNABTK08, TNABTK09, TNABTK10,
TNABTK11, TNAATK00, TNAATK01, TNAATK02, TNAATK03, TNAATK04, TNAATK05, TNAATK06, TNAATK07, TNAATK08, TNAATK09, TNAATK10, TNAATK11, TNAZTK00,
TNAZTK01, TNAZTK02, TNAZTK03, TNAZTK04, TNAZTK05, TNAZTK06, TNAZTK07, TNAZTK08, TNAZTK09, TNAZTK10, TNAZTK11, LSTUKEDT, LSTUKETK, LSTHARDT,
HINZEIKB, ZEIRNKKB, ZEIRT, HINKB, ZAIKB, UNTCD00, UNTCD01, UNTCD02, UNTNM00, UNTNM01, UNTNM02, IRIASU00, IRIASU01, IRIASU02, HINTKSID, HINJUNKB,
HINNMMKB, IMGNM, JANCD, ITFCD, MRPKB, HRTDD, ORTDD, COLCD, SIZCD, JYURY, YOURY, LOTKB, HINLCDKB, NSZHYJKB, HINLBLKB, AUTLOCID, HATLOTSU,
HATCYLID, KAMCLKB, RELFL, QSYOMKB, QSYOMKSU, QSYOMHSU, QJYURY, QUNSKSU, QLSTURDT, QHIKHSU, QKEISANF, TNATKKB, GENTKAKB, QGNRHTK, QRMHTK,
QKEIHTK, QGRYOKB, QPRDCD, QPRDKB, QKOSKB, QSZUNTCD, QSZUNTNM, QHIKSSB, QHNUNTCD, QHNUNTNM, QKOUNTCD, QKOUNTNM, STTYUNDT, ENDYUNDT,
STTYUGDT, ENDYUGDT, TFKHTK, JYURYCNV, QZAIALKB, HINLCDSB, SPCDT, SPCHANSU, ITFBCD, ITFCCD, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO,
MAKHINCD, SEIHINNMA, SEIHINNMB, SEIYURKB, HOKTEKKB, HATUNTCD, HANUNTCD, TRISTPKB, EANKB, USEKB, HATUNTIN, HANUNTIN, MPDMSTKB, HINHIKTM,
OLDHINCD, MEDCD, MEDACD, MEDBCD, MEDCCD, KOURITK, OROSITK, TOKUYATK, KNRTK, IYAKUKB, DOUYAKKB, DEKYAKKB, KITGIMKB, HOKSEIKB, SYOKANKB,
HOKANKB, TEHAIKB, TZCCD, KSSYOCD, MEKTM, SYOTM, OTPUNTSU, TRISTPDT, HATCD, SODIRISU, MDNOUTKB, IJICDA, IJICDB, KTKBCDA, KTKBCDB, KTKBCDC,
KTKBCDD, KTKBCDE, KTKBCDF, KTKBCDG, KTKBCDH, KTKBCDI, KTKBCDJ, KBYBCDA, KBYBCDB, KBYBCDC, KBYBCDD, KBYBCDE, SIYKB, JAN4CD, COMHINCD,
SUCHINCD, DIRISU, IRITANSU, HINBUNCD, GTINCD, HIKSYRKB, JDHINNK, JSHINNK, JSTRISTTDT, JSTRISTPDT, KIHIRISU, PLTTUMSU, CASGWSU, CASGWUNTCD,
CASSZLSU, CASSZWSU, CASSZHSU, CASSZUNTCD, CASCPSU, CASCPUNTCD, PCEGWSU, PCEGWUNTCD, PCESZLSU, PCESZWSU, PCESZHSU, PCESZUNTCD, PCECPSU,
PCECPUNTCD, NHSKTKB00, NHSKTKB01, NHSKTKB02, NHSKTKB03, YAKKATK, OUTKB, OUTDT, SEISKB
FROM OPENQUERY(ORCL,
'
SELECT
DATKB, HINMSTKB, HINCD, HINNMA, HINNMB, HINNK, HINCLAKB, HINCLBKB, HINCLCKB, HINCLAID, HINCLBID, HINCLCID, HINSIRCD, MAKCD, HINCMA,
HINCMB, HINCMC, HINCMD, HINCME, TNABTK00, TNABTK01, TNABTK02, TNABTK03, TNABTK04, TNABTK05, TNABTK06, TNABTK07, TNABTK08, TNABTK09, TNABTK10,
TNABTK11, TNAATK00, TNAATK01, TNAATK02, TNAATK03, TNAATK04, TNAATK05, TNAATK06, TNAATK07, TNAATK08, TNAATK09, TNAATK10, TNAATK11, TNAZTK00,
TNAZTK01, TNAZTK02, TNAZTK03, TNAZTK04, TNAZTK05, TNAZTK06, TNAZTK07, TNAZTK08, TNAZTK09, TNAZTK10, TNAZTK11, LSTUKEDT, LSTUKETK, LSTHARDT,
HINZEIKB, ZEIRNKKB, ZEIRT, HINKB, ZAIKB, UNTCD00, UNTCD01, UNTCD02, UNTNM00, UNTNM01, UNTNM02, IRIASU00, IRIASU01, IRIASU02, HINTKSID, HINJUNKB,
HINNMMKB, IMGNM, JANCD, ITFCD, MRPKB, HRTDD, ORTDD, COLCD, SIZCD, JYURY, YOURY, LOTKB, HINLCDKB, NSZHYJKB, HINLBLKB, AUTLOCID, HATLOTSU,
HATCYLID, KAMCLKB, RELFL, QSYOMKB, QSYOMKSU, QSYOMHSU, QJYURY, QUNSKSU, QLSTURDT, QHIKHSU, QKEISANF, TNATKKB, GENTKAKB, QGNRHTK, QRMHTK,
QKEIHTK, QGRYOKB, QPRDCD, QPRDKB, QKOSKB, QSZUNTCD, QSZUNTNM, QHIKSSB, QHNUNTCD, QHNUNTNM, QKOUNTCD, QKOUNTNM, STTYUNDT, ENDYUNDT,
STTYUGDT, ENDYUGDT, TFKHTK, JYURYCNV, QZAIALKB, HINLCDSB, SPCDT, SPCHANSU, ITFBCD, ITFCCD, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO,
MAKHINCD, SEIHINNMA, SEIHINNMB, SEIYURKB, HOKTEKKB, HATUNTCD, HANUNTCD, TRISTPKB, EANKB, USEKB, HATUNTIN, HANUNTIN, MPDMSTKB, HINHIKTM,
OLDHINCD, MEDCD, MEDACD, MEDBCD, MEDCCD, KOURITK, OROSITK, TOKUYATK, KNRTK, IYAKUKB, DOUYAKKB, DEKYAKKB, KITGIMKB, HOKSEIKB, SYOKANKB,
HOKANKB, TEHAIKB, TZCCD, KSSYOCD, MEKTM, SYOTM, OTPUNTSU, TRISTPDT, HATCD, SODIRISU, MDNOUTKB, IJICDA, IJICDB, KTKBCDA, KTKBCDB, KTKBCDC,
KTKBCDD, KTKBCDE, KTKBCDF, KTKBCDG, KTKBCDH, KTKBCDI, KTKBCDJ, KBYBCDA, KBYBCDB, KBYBCDC, KBYBCDD, KBYBCDE, SIYKB, JAN4CD, COMHINCD,
SUCHINCD, DIRISU, IRITANSU, HINBUNCD, GTINCD, HIKSYRKB, JDHINNK, JSHINNK, JSTRISTTDT, JSTRISTPDT, KIHIRISU, PLTTUMSU, CASGWSU, CASGWUNTCD,
CASSZLSU, CASSZWSU, CASSZHSU, CASSZUNTCD, CASCPSU, CASCPUNTCD, PCEGWSU, PCEGWUNTCD, PCESZLSU, PCESZWSU, PCESZHSU, PCESZUNTCD, PCECPSU,
PCECPUNTCD, NHSKTKB00, NHSKTKB01, NHSKTKB02, NHSKTKB03, YAKKATK, OUTKB, OUTDT, SEISKB
FROM NSY_USR1.HINMTA
')
;

--ビュー：o_HINMTC
--FROM: [ORCL-LINK].ORCLLINK.dbo.HINMTC
CREATE OR ALTER o_HINMTC AS
SELECT
SOUCD, HINCD, LOTID, HINLCDDT, HINLCDKB, LOTCM, RELZAISU, FIXLOCID, FSTNYUDT,FSTSYUDT, LSTNYUDT, LSTSYUDT, HINMSTKB, RELFL, OPEID, CLTID,
WRTTM,WRTDT, HIKSU, GNKTK, ZNETNADT, ZNETNASU, ZNETNAKN, ZNEBZNSU,SMAZANDT, SMAZANSU, SMAZANKN, SMABZNSU, LOTAID, LOTBID
FROM OPENQUERY(ORCL,
'
SELECT
SOUCD, HINCD, LOTID, HINLCDDT, HINLCDKB, LOTCM, RELZAISU, FIXLOCID, FSTNYUDT,FSTSYUDT, LSTNYUDT, LSTSYUDT, HINMSTKB, RELFL, OPEID, CLTID,
WRTTM, WRTDT, HIKSU, GNKTK, ZNETNADT, ZNETNASU, ZNETNAKN, ZNEBZNSU,SMAZANDT, SMAZANSU, SMAZANKN, SMABZNSU, LOTAID, LOTBID
FROM NSY_USR1.HINMTC
where ((LOTID <> '' '')or(FSTSYUDT <> '' ''))
')
;

--ビュー：o_IDNTHA
--FROM: [ORCL-LINK].ORCLLINK.dbo.IDNTHA
CREATE OR ALTER o_IDNTHA AS
SELECT
DATNO, DATKB, DENKB, IDNNO, HDNNO, IDNDT, SMADT, SIRCD, SIRRN,TANCD, KTNCD, SOUCD, TANBMNCD, SOUBMNCD, DENCM, DENCMB, SIRNMMKB,
SDNID, LSTID, SIRMSTKB, TANMSTKB, DKBSB, SDNENDKB, LSTTORDT,OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, JHDCNTNO, HDNSMEKB,IDNSMEKB, UHAKB, DWHKB
FROM OPENQUERY(ORCL,
'
SELECT
DATNO, DATKB, DENKB, IDNNO, HDNNO, IDNDT, SMADT, SIRCD, SIRRN,TANCD, KTNCD, SOUCD, TANBMNCD, SOUBMNCD, DENCM, DENCMB, SIRNMMKB,
SDNID, LSTID, SIRMSTKB, TANMSTKB, DKBSB, SDNENDKB, LSTTORDT,OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, JHDCNTNO, HDNSMEKB,IDNSMEKB, UHAKB, DWHKB
FROM NSY_USR1.IDNTHA
WHERE DATKB =''1''
')
;

--ビュー：o_IDNTRA
--FROM: [ORCL-LINK].ORCLLINK.dbo.IDNTRA
CREATE OR ALTER o_IDNTRA AS
SELECT
DATNO, DATKB, DENKB, IDNNO, LINNO, HDNNO, HDNLINNO, RECNO, IDNRECNO, IDNDT, SMADT, SIRCD, TANCD, KTNCD, SOUCD, TANBMNCD, SOUBMNCD,
HINCD, HINNMA, HINNMB, MAKCD, HINSIRCD, HINNMMKB, HINKB, ZAIKB, MRPKB, HRTDD, ORTDD, SIZCD, COLCD, UNTCD00, UNTCD01, UNTCD02, UNTNM00,
UNTNM01, UNTNM02, IRISU00, IRISU01, IRISU02, CASSU00, CASSU01, CASSU02, INPSU, SRESU, LINCMA, LINCMB, HATDELSU, LSTID, SIRMSTKB, TANMSTKB,
HINMSTKB, DKBSB, DKBID, DKBNM, UPDID, MHJSQ, DKBZAIFL, NSZHYJKB, LOTKB, HINLCDKB, SUBDSPKB, HEDLOTID, HEDLCTDT, DSPUNTCD, DSPUNTIN,
DSPUNTNM, DSPIRISU, DSPCASSU, DKBFLA, DKBFLB, DKBFLC, DFLDKBCD, OPEID, CLTID, WRTTM, WRTDT, TOKCD, SIRTNKKB, MPDSEQNO, ODNNO, DWHKB, LOTAID,LOTBID, NYUYOTNO
FROM OPENQUERY(ORCL,
'
SELECT
DATNO, DATKB, DENKB, IDNNO, LINNO, HDNNO, HDNLINNO, RECNO, IDNRECNO, IDNDT, SMADT, SIRCD, TANCD, KTNCD, SOUCD, TANBMNCD, SOUBMNCD,
HINCD, HINNMA, HINNMB, MAKCD, HINSIRCD, HINNMMKB, HINKB, ZAIKB, MRPKB, HRTDD, ORTDD, SIZCD, COLCD, UNTCD00, UNTCD01, UNTCD02, UNTNM00,
UNTNM01, UNTNM02, IRISU00, IRISU01, IRISU02, CASSU00, CASSU01, CASSU02, INPSU, SRESU, LINCMA, LINCMB, HATDELSU, LSTID, SIRMSTKB, TANMSTKB,
HINMSTKB, DKBSB, DKBID, DKBNM, UPDID, MHJSQ, DKBZAIFL, NSZHYJKB, LOTKB, HINLCDKB, SUBDSPKB, HEDLOTID, HEDLCTDT, DSPUNTCD, DSPUNTIN,
DSPUNTNM, DSPIRISU, DSPCASSU, DKBFLA, DKBFLB, DKBFLC, DFLDKBCD, OPEID, CLTID, WRTTM, WRTDT, TOKCD, SIRTNKKB, MPDSEQNO, ODNNO, DWHKB, LOTAID,LOTBID, NYUYOTNO
FROM NSY_USR1.IDNTRA
WHERE DATKB = ''1''
')
;

--ビュー：o_IRITRA
--FROM: [ORCL-LINK].ORCLLINK.dbo.IRITRA
CREATE OR ALTER o_IRITRA AS
SELECT
DATNO, DATKB, DENKB, QIRNO, LINNO, HINCD, HINNMA, HINNMB, MAKCD, HINSIRCD, HINKB, ZAIKB, MRPKB, KOSCASSU, HRTDD, ORTDD, SIZCD, COLCD,
UNTCD00, UNTCD01, UNTCD02, UNTNM00, UNTNM01, UNTNM02, IRISU00, IRISU01, IRISU02, CASSU00, CASSU01, CASSU02, FURSU, GNKFRITK, GNKFRIKN, LINCMA,
LINCMB, LSTID, HINMSTKB, DKBSB, DKBID, DKBNM, UPDID, MHJSQ, DKBTEGFL, DKBZAIFL, LOTKB, HINLCDKB, SUBDSPKB, HEDLOTID, HEDLCTDT, DSPUNTCD,
DSPUNTIN, DSPUNTNM, DSPIRISU, DSPCASSU, DKBFLA, DKBFLB, DKBFLC, DFLDKBCD, ARGGSGTK, ARGGSGKN, OPEID, CLTID, WRTTM, WRTDT, SYUSIJNO
FROM OPENQUERY(ORCL,
'
SELECT
DATNO, DATKB, DENKB, QIRNO, LINNO, HINCD, HINNMA, HINNMB, MAKCD, HINSIRCD, HINKB, ZAIKB, MRPKB, KOSCASSU, HRTDD, ORTDD, SIZCD, COLCD,
UNTCD00, UNTCD01, UNTCD02, UNTNM00, UNTNM01, UNTNM02, IRISU00, IRISU01, IRISU02, CASSU00, CASSU01, CASSU02, FURSU, GNKFRITK, GNKFRIKN, LINCMA,
LINCMB, LSTID, HINMSTKB, DKBSB, DKBID, DKBNM, UPDID, MHJSQ, DKBTEGFL, DKBZAIFL, LOTKB, HINLCDKB, SUBDSPKB, HEDLOTID, HEDLCTDT, DSPUNTCD,
DSPUNTIN, DSPUNTNM, DSPIRISU, DSPCASSU, DKBFLA, DKBFLB, DKBFLC, DFLDKBCD, ARGGSGTK, ARGGSGKN, OPEID, CLTID, WRTTM, WRTDT, SYUSIJNO
FROM NSY_USR1.IRITRA
')
;

--ビュー：o_JDNTHA
--FROM: [ORCL-LINK].ORCLLINK.[dbo].[w_JDNTHA_BF2M] UNION ALL [ORCL-LINK].ORCLLINK.[dbo].[v_JDNTHA_2M]
CREATE OR ALTER o_JDNTHA AS
SELECT
*
FROM OPENQUERY(ORCL,
'
select
*
from NSY_USR1.JDNTHA
WHERE DATKB = ''1''
')
;

--ビュー：o_JDNTHA_20150625そのまま全参照版
--FROM: [ORCL-LINK].ORCLLINK.dbo.JDNTHA
CREATE OR ALTER o_JDNTHA_20150625そのまま全参照版 AS
SELECT
DATNO, DATKB, DENKB, JDNNO, JDNDT, DEFNOKDT, JUCSYYDT, SMADT, TOKCD, TOKRN, NHSCD, NHSRN, TOKSEICD, TANCD, KTNCD, SOUCD, TANBMNCD,
TOKBMNCD, SOUBMNCD, SBAUODKN, SBAJZEKN, SBAJZKKN, SYUBACID, ROTCD, ROTSHPSQ, DENCM, DENCMB, TOKSMEKB, TOKSMEDD, TOKSMECC, TOKSDWKB,
TOKKESDD, TOKKESCC, TOKKDWKB, TOKZEIKB, TOKZCLKB, TOKRPSKB, TOKZRNKB, TOKNMMKB, NHSNMMKB, ADNID, LSTID, TOKMSTKB, NHSMSTKB, TANMSTKB,
NHSKB, DKBSB, TOKNKDKB, JDNENDKB, ODNKB, ODNENDKB, UDNENDKB, SVCKB, SVCENDKB, URIKJNKB, LSTTORDT, MOTDATNO, OPEID, CLTID, WRTTM, WRTDT,
CRTTM, CRTDT, UPDCNTNO, TRNNO, CSVDATNO, JHAKB, JDNSMEKB, TOKCLAKB, TOKCLBKB, TOKCLCKB, TOKCLAID, TOKCLBID, TOKCLCID, PIKHAKKB, SBAGNKKN,
ALSKB, KRDKB, JUCKB, HSSRN, HSSZP, HSSADA, HSSADB, HSSADC, HSSTL, HSSFX, DENCMBCD, DENCMCCD, DENCMC, QUNSID
FROM OPENQUERY(ORCL,
'
SELECT * FROM NSY_USR1.JDNTHA
')
;

--ビュー：o_JDNTRA
--FROM: [ORCL-LINK].ORCLLINK.dbo.JDNTRA
CREATE OR ALTER o_JDNTRA AS
SELECT
*
FROM OPENQUERY(ORCL,
'
select
*
from NSY_USR1.JDNTRA
WHERE DATKB = ''1''
')
;
/*要らないカラム:
HRTDD,ORTDD,SIZCD,UNTCD01,UNTCD02,UNTMN01,UNTMN02,SYUBACID,ROTID,ROTSHPSQ,LINCMA,LINCMB,DKBFLA,DKBFLB,DKBFLC,DFLDKBCD,MOTDATNO,HDNNO,JIGCD,JIGNM,MAKHINCD,EOSHINID,EOSHINNA,EOSHINNB,AUTHDNNO,SIRTNKKB,ERRCM
*/


--ビュー：o_JGTTRA_1M
--FROM: [ORCL-LINK].ORCLLINK.dbo.JGTTRA_1M
CREATE OR ALTER o_JGTTRA_1M AS
SELECT
DATNO, LINNO, UPDMODKB, CSVDATNO, CSVLINNO, MDSHIKIB, MDOROCD, MDIRYOCD, MDSUBNO, MDCRTDT, MDCRTTM, MDHATNO, MDFUKCD, MDHATDT,
MDHINKB, MDGTINCD, MDGTINNM, MDHATSU, MDNOKDT, MDNHSBA, MDMAEKB, MDMAECD, TOKCD, NHSCD, SOUCD, TANCD, JDNDT, DKBID, HINCD, UODTK,
UODKN, ERRNO, ERRCM, JDNNO, JDNLINNO, SYONO, OPEID, CLTID, WRTTM, WRTDT, JUCSYYDT, STSFL, SYODT
FROM OPENQUERY(ORCL,
'
SELECT
DATNO, LINNO, UPDMODKB, CSVDATNO, CSVLINNO, MDSHIKIB, MDOROCD, MDIRYOCD, MDSUBNO, MDCRTDT, MDCRTTM, MDHATNO, MDFUKCD, MDHATDT,
MDHINKB, MDGTINCD, MDGTINNM, MDHATSU, MDNOKDT, MDNHSBA, MDMAEKB, MDMAECD, TOKCD, NHSCD, SOUCD, TANCD, JDNDT, DKBID, HINCD, UODTK,
UODKN, ERRNO, ERRCM, JDNNO, JDNLINNO, SYONO, OPEID, CLTID, WRTTM, WRTDT, JUCSYYDT, STSFL, SYODT
FROM NSY_USR1.JGTTRA
where SYODT >= to_char(ADD_MONTHS(sysdate, - 1), ''yyyymmdd'')
')
;
