/**
2024.07.01 y.takeda
説明：120.6(SQL Server)の各種伝票ビューを120.12(Oracle)を直接参照する形式に変更する
DB: 192.168.120.6 > cocktail > ビュー
*/

--ビュー名：m_カクテル取引先県マスタ
--FROM: dbo.o_CLSMTA
select
    RTRIM(CLSID) as 県コード
    ,RTRIM(CLSNM) as 県名
from dbo.o_CLSMTA
where CLSKB='0'
;

--ビュー名：m_カクテル商品科目分類マスタ
--FROM: dbo.o_MEIMTA
select
    TOP(100) percent
    RTRIM(MEICD) as 科目分類コード
    ,RTRIM(MEINM) as 科目分類名
    ,RTRIM(MEIRN) as 科目分類略称
from dbo.o_MEIMTA
where MEISB = '02'
order by 科目分類コード
;

--ビュー名：m_カクテル商品規制区分マスタ
--FROM: dbo.o_MEIMTA
select
    TOP(100) percent
    RTRIM(MEICD) as 規制分類コード
    ,RTRIM(MEINM) as 規制分類名
    ,RTRIM(MEIRN) as 規制分類略称
from dbo.o_MEIMTA
where MEISB = '83'
order by 規制分類コード
;

--ビュー名：m_カクテル商品区分マスタ
--FROM: dbo.o_CLSMTA
select
    TOP(100) percent
    RTRIM(CLSID) as 商品区分コード
    ,RTRIM(CLSNM) as 商品区分名
from dbo.o_CLSMTA
where CLSKB='7'
order by 商品区分コード
;

--ビュー名：m_カクテル商品剤型区分マスタ
--FROM: dbo.o_CLSMTA
select
    TOP(100) percent
    RTRIM(CLSID) as 剤型区分コード
    ,RTRIM(CLSNM) as 剤型区分名
from dbo.o_CLSMTA
where CLSKB='8'
order by 剤型区分コード
;

--ビュー名：m_カクテル商品受注分類マスタ
--FROM: dbo.o_MEIMTA
select
    RTRIM(MEICD) as 受注分類コード
    ,RTRIM(MEINM) as 受注分類名
    ,RTRIM(MEIRN) as 受注分類略称
from dbo.o_MEIMTA
where MEISB='81'
;

--ビュー名：m_カクテル商品単価ランクマスタ
--FROM: dbo.o_MEIMTA
select
    TOP(100) percent
    RTRIM(MEICD) as 単価ランク区分コード
    ,RTRIM(MEINM) as 単価ランク名
    ,RTRIM(MEIRN) as 単価ランク略称
from dbo.o_MEIMTA
where MEISB='01'
order by 単価ランク区分コード
;

--ビュー名：m_カクテル商品薬効区分マスタ
--FROM: dbo.o_CLSMTA
select
    TOP(100) percent
    RTRIM(CLSID) as 薬効区分コード
    ,RTRIM(CLSNM) as 薬効区分名
from dbo.o_CLSMTA
where CLSKB = '9'
order by 薬効区分コード
;

--ビュー名：m_カクテル部門マスタ
--FROM: dbo.o_BMNMTA
select
    RTRIM(BMNCD) as 部門コード
    ,RTRIM(BMNNM) as 部門名
    ,RTRIM(BMNNK) as 部門カナ
    ,RTRIM(BMNZP) as 部門郵便番号
    ,RTRIM(BMNADA) as 部門住所1
    ,RTRIM(BMNADB) as 部門住所2
    ,RTRIM(BMNADC) AS 部門住所3
    ,RTRIM(BMNTL) AS 部門電話番号
    ,RTRIM(BMNFX) AS 部門FAX番号
from dbo.o_BMNMTA
;

--ビュー名：m_取引先得意先種別マスタ
--FROM: dbo.o_CLSMTA
SELECT
    TOP (100) PERCENT
    RTRIM(CLSID) AS 得意先種別コード
    ,RTRIM(CLSNM) AS 得意先種別名
from dbo.o_CLSMTA
where (CLSKB = '1')
order by 得意先種別コード
;

--ビュー：o_BMNMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.BMNMTA
SELECT
DATKB, BMNMSTKB, BMNCD, BMNNM, BMNNK, BMNZP, BMNADA, BMNADB, BMNADC,BMNTL, BMNFX, BMNCLAKB, BMNCLBKB, BMNCLCKB, BMNCLAID, BMNCLBID,BMNCLCID, KEIBUMCD, RELFL, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, MPDMSTKB
FROM OPENQUERY(ORCL,
'
SELECT
DATKB, BMNMSTKB, BMNCD, BMNNM, BMNNK, BMNZP, BMNADA, BMNADB, BMNADC,BMNTL, BMNFX, BMNCLAKB, BMNCLBKB, BMNCLCKB, BMNCLAID, BMNCLBID,BMNCLCID, KEIBUMCD, RELFL, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO, MPDMSTKB
FROM NSY_USR1.BMNMTA
WHERE DATKB = ''1''
')
;

--ビュー：o_BMKMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.BMKMTA
SELECT
DATKB, BNKCD, BNKNM, BNKKMKCD00, BNKKMKCD01,KOZID00, KOZID01, RELFL, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM OPENQUERY(ORCL,
'SELECT
DATKB, BNKCD, BNKNM, BNKKMKCD00, BNKKMKCD01,KOZID00, KOZID01, RELFL, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM NSY_USR1.BNKMTA
WHERE DATKB =''1''
')
;

--ビュー：o_CLSMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.CLSMTA
SELECT CLSKB, CLSID, CLSNM, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM OPENQUERY(ORCL,
'SELECT CLSKB, CLSID, CLSNM, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO
FROM NSY_USR1.CLSMTA
')
;

--ビュー：o_HINMTA
--FROM: [ORCL-LINK].ORCLLINK.dbo.HINMTA
SELECT
DATKB, HINMSTKB, HINCD, HINNMA, HINNMB, HINNK, HINCLAKB, HINCLBKB, HINCLCKB, HINCLAID, HINCLBID, HINCLCID, HINSIRCD, MAKCD, HINCMA,
HINCMB, HINCMC, HINCMD, HINCME, TNABTK00, TNABTK01, TNABTK02, TNABTK03, TNABTK04, TNABTK05, TNABTK06, TNABTK07, TNABTK08, TNABTK09, TNABTK10,
TNABTK11, TNAATK00, TNAATK01, TNAATK02, TNAATK03, TNAATK04, TNAATK05, TNAATK06, TNAATK07, TNAATK08, TNAATK09, TNAATK10, TNAATK11, TNAZTK00,
TNAZTK01, TNAZTK02, TNAZTK03, TNAZTK04, TNAZTK05, TNAZTK06, TNAZTK07, TNAZTK08, TNAZTK09, TNAZTK10, TNAZTK11, LSTUKEDT, LSTUKETK, LSTHARDT,
HINZEIKB, ZEIRNKKB, ZEIRT, HINKB, ZAIKB, UNTCD00, UNTCD01, UNTCD02, UNTNM00, UNTNM01, UNTNM02, IRIASU00, IRIASU01, IRIASU02, HINTKSID, HINJUNKB,
HINNMMKB, IMGNM, JANCD, ITFCD, MRPKB, HRTDD, ORTDD, COLCD, SIZCD, JYURY, YOURY, LOTKB, HINLCDKB, NSZHYJKB, HINLBLKB, AUTLOCID, HATLOTSU,
HATCYLID, KAMCLKB, RELFL, QSYOMKB, QSYOMKSU, QSYOMHSU, QJYURY, QUNSKSU, QLSTURDT, QHIKHSU, QKEISANF, TNATKKB, GENTKAKB, QGNRHTK, QRMHTK,
QKEIHTK, QGRYOKB, QPRDCD, QPRDKB, QKOSKB, QSZUNTCD, QSZUNTNM, QHIKSSB, QHNUNTCD, QHNUNTNM, QKOUNTCD, QKOUNTNM, STTYUNDT, ENDYUNDT,
STTYUGDT, ENDYUGDT, TFKHTK, JYURYCNV, QZAIALKB, HINLCDSB, SPCDT, SPCHANSU, ITFBCD, ITFCCD, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO,
MAKHINCD, SEIHINNMA, SEIHINNMB, SEIYURKB, HOKTEKKB, HATUNTCD, HANUNTCD, TRISTPKB, EANKB, USEKB, HATUNTIN, HANUNTIN, MPDMSTKB, HINHIKTM,
OLDHINCD, MEDCD, MEDACD, MEDBCD, MEDCCD, KOURITK, OROSITK, TOKUYATK, KNRTK, IYAKUKB, DOUYAKKB, DEKYAKKB, KITGIMKB, HOKSEIKB, SYOKANKB,
HOKANKB, TEHAIKB, TZCCD, KSSYOCD, MEKTM, SYOTM, OTPUNTSU, TRISTPDT, HATCD, SODIRISU, MDNOUTKB, IJICDA, IJICDB, KTKBCDA, KTKBCDB, KTKBCDC,
KTKBCDD, KTKBCDE, KTKBCDF, KTKBCDG, KTKBCDH, KTKBCDI, KTKBCDJ, KBYBCDA, KBYBCDB, KBYBCDC, KBYBCDD, KBYBCDE, SIYKB, JAN4CD, COMHINCD,
SUCHINCD, DIRISU, IRITANSU, HINBUNCD, GTINCD, HIKSYRKB, JDHINNK, JSHINNK, JSTRISTTDT, JSTRISTPDT, KIHIRISU, PLTTUMSU, CASGWSU, CASGWUNTCD,
CASSZLSU, CASSZWSU, CASSZHSU, CASSZUNTCD, CASCPSU, CASCPUNTCD, PCEGWSU, PCEGWUNTCD, PCESZLSU, PCESZWSU, PCESZHSU, PCESZUNTCD, PCECPSU,
PCECPUNTCD, NHSKTKB00, NHSKTKB01, NHSKTKB02, NHSKTKB03, YAKKATK, OUTKB, OUTDT, SEISKB
FROM OPENQUERY(ORCL,
'
SELECT
DATKB, HINMSTKB, HINCD, HINNMA, HINNMB, HINNK, HINCLAKB, HINCLBKB, HINCLCKB, HINCLAID, HINCLBID, HINCLCID, HINSIRCD, MAKCD, HINCMA,
HINCMB, HINCMC, HINCMD, HINCME, TNABTK00, TNABTK01, TNABTK02, TNABTK03, TNABTK04, TNABTK05, TNABTK06, TNABTK07, TNABTK08, TNABTK09, TNABTK10,
TNABTK11, TNAATK00, TNAATK01, TNAATK02, TNAATK03, TNAATK04, TNAATK05, TNAATK06, TNAATK07, TNAATK08, TNAATK09, TNAATK10, TNAATK11, TNAZTK00,
TNAZTK01, TNAZTK02, TNAZTK03, TNAZTK04, TNAZTK05, TNAZTK06, TNAZTK07, TNAZTK08, TNAZTK09, TNAZTK10, TNAZTK11, LSTUKEDT, LSTUKETK, LSTHARDT,
HINZEIKB, ZEIRNKKB, ZEIRT, HINKB, ZAIKB, UNTCD00, UNTCD01, UNTCD02, UNTNM00, UNTNM01, UNTNM02, IRIASU00, IRIASU01, IRIASU02, HINTKSID, HINJUNKB,
HINNMMKB, IMGNM, JANCD, ITFCD, MRPKB, HRTDD, ORTDD, COLCD, SIZCD, JYURY, YOURY, LOTKB, HINLCDKB, NSZHYJKB, HINLBLKB, AUTLOCID, HATLOTSU,
HATCYLID, KAMCLKB, RELFL, QSYOMKB, QSYOMKSU, QSYOMHSU, QJYURY, QUNSKSU, QLSTURDT, QHIKHSU, QKEISANF, TNATKKB, GENTKAKB, QGNRHTK, QRMHTK,
QKEIHTK, QGRYOKB, QPRDCD, QPRDKB, QKOSKB, QSZUNTCD, QSZUNTNM, QHIKSSB, QHNUNTCD, QHNUNTNM, QKOUNTCD, QKOUNTNM, STTYUNDT, ENDYUNDT,
STTYUGDT, ENDYUGDT, TFKHTK, JYURYCNV, QZAIALKB, HINLCDSB, SPCDT, SPCHANSU, ITFBCD, ITFCCD, OPEID, CLTID, WRTTM, WRTDT, UPDCNTNO, TRNNO,
MAKHINCD, SEIHINNMA, SEIHINNMB, SEIYURKB, HOKTEKKB, HATUNTCD, HANUNTCD, TRISTPKB, EANKB, USEKB, HATUNTIN, HANUNTIN, MPDMSTKB, HINHIKTM,
OLDHINCD, MEDCD, MEDACD, MEDBCD, MEDCCD, KOURITK, OROSITK, TOKUYATK, KNRTK, IYAKUKB, DOUYAKKB, DEKYAKKB, KITGIMKB, HOKSEIKB, SYOKANKB,
HOKANKB, TEHAIKB, TZCCD, KSSYOCD, MEKTM, SYOTM, OTPUNTSU, TRISTPDT, HATCD, SODIRISU, MDNOUTKB, IJICDA, IJICDB, KTKBCDA, KTKBCDB, KTKBCDC,
KTKBCDD, KTKBCDE, KTKBCDF, KTKBCDG, KTKBCDH, KTKBCDI, KTKBCDJ, KBYBCDA, KBYBCDB, KBYBCDC, KBYBCDD, KBYBCDE, SIYKB, JAN4CD, COMHINCD,
SUCHINCD, DIRISU, IRITANSU, HINBUNCD, GTINCD, HIKSYRKB, JDHINNK, JSHINNK, JSTRISTTDT, JSTRISTPDT, KIHIRISU, PLTTUMSU, CASGWSU, CASGWUNTCD,
CASSZLSU, CASSZWSU, CASSZHSU, CASSZUNTCD, CASCPSU, CASCPUNTCD, PCEGWSU, PCEGWUNTCD, PCESZLSU, PCESZWSU, PCESZHSU, PCESZUNTCD, PCECPSU,
PCECPUNTCD, NHSKTKB00, NHSKTKB01, NHSKTKB02, NHSKTKB03, YAKKATK, OUTKB, OUTDT, SEISKB
FROM NSY_USR1.HINMTA
')
;
